#!/bin/sh
files=""
files="$files SDL-1.2.15.tar.gz"
files="$files SDL2-2.0.3.tar.gz"
files="$files freetype-2.5.3.tar.bz2"
files="$files gmp-6.0.0a.tar.bz2"
files="$files jpegsrc.v9a.tar.gz"
files="$files libpng-1.6.12.tar.gz"
files="$files onig-5.9.5.tar.gz"
files="$files tiff-3.8.2.tar.gz"
files="$files wxWidgets-3.0.1.tar.bz2"
files="$files yaml-0.1.5.tar.gz"
for file in $files
do
	echo $file
	curl -O http://www.gura-lang.org/guests/$file
done
