.TH man 1 "15 Nov 2013" "0.4.0" "gura man page"
.SH NAME
gura \- interpreter of Gura programming language
.SH SYNOPSIS
.B gura [\fIOPTIONS\fR] [\fIFILE\fR] [\fIARGS\fR] ...

.SH DESCRIPTION
This program is an interpreter of the Gura programming language.

.SH OPTIONS

.TP
\fB\-\-help\fR
Print a help.

.SH SEE ALSO

.SH BUGS

.SH AUTHOR
ypsitau (ypsitau@nifty.com)
