#!/bin/bash
files=
files="$files test-application.gura"
files="$files test-binary.gura"
files="$files test-block.gura"
files="$files test-codec.gura"
files="$files test-color.gura"
files="$files test-complex.gura"
files="$files test-csv.gura"
files="$files test-datetime.gura"
files="$files test-declaration.gura"
files="$files test-dict.gura"
files="$files test-diff.gura"
files="$files test-error.gura"
files="$files test-expr.gura"
files="$files test-filter.gura"
files="$files test-formatter.gura"
files="$files test-fraction.gura"
files="$files test-fs.gura"
files="$files test-function.gura"
files="$files test-hash.gura"
files="$files test-image.gura"
files="$files test-list-iterator.gura"
files="$files test-map.gura"
files="$files test-markdown.gura"
files="$files test-math.gura"
files="$files test-matrix.gura"
#files="$files test-midi.gura"
files="$files test-module.gura"
files="$files test-object.gura"
files="$files test-opengl.gura"
files="$files test-operator.gura"
files="$files test-optimize.gura"
files="$files test-path.gura"
files="$files test-re.gura"
files="$files test-repeater.gura"
files="$files test-sqlite3.gura"
files="$files test-stream.gura"
files="$files test-string.gura"
files="$files test-template.gura"
files="$files test-value.gura"
files="$files test-xml.gura"
files="$files test-xhtml.gura"
files="$files test-yaml.gura"

if [ "$1" = "" ]; then
	for file in $files
	do
		echo $file
		gura $file > result/${file%.gura}.result.txt
		diff -u --strip-trailing-cr result/${file%.gura}.sample.txt result/${file%.gura}.result.txt
	done	
elif [ "$1" = "genscript" ]; then
	for file in $files
	do
		echo $file
		gura genscript.gura --eval $file > result/${file%.gura}.result.txt
		diff -u --strip-trailing-cr result/${file%.gura}.sample.txt result/${file%.gura}.result.txt
	done	
elif [ "$1" = "update" ]; then
	for file in $files
	do
		echo $file
		gura $file > result/${file%.gura}.sample.txt
	done	
else
	file="test-$1.gura"
	echo $file
	gura $file > result/${file%.gura}.result.txt
	diff -u --strip-trailing-cr result/${file%.gura}.sample.txt result/${file%.gura}.result.txt
fi
