#!/bin/bash
cases=
cases="$cases test-application.gura"
cases="$cases test-binary.gura"
cases="$cases test-block.gura"
cases="$cases test-codec.gura"
cases="$cases test-color.gura"
cases="$cases test-complex.gura"
cases="$cases test-csv.gura"
cases="$cases test-datetime.gura"
cases="$cases test-declaration.gura"
cases="$cases test-dict.gura"
cases="$cases test-diff.gura"
cases="$cases test-error.gura"
cases="$cases test-expr.gura"
cases="$cases test-filter.gura"
cases="$cases test-formatter.gura"
cases="$cases test-fraction.gura"
cases="$cases test-fs.gura"
cases="$cases test-function.gura"
cases="$cases test-hash.gura"
cases="$cases test-image.gura"
cases="$cases test-list-iterator.gura"
cases="$cases test-map.gura"
cases="$cases test-markdown.gura"
cases="$cases test-math.gura"
cases="$cases test-matrix.gura"
#cases="$cases test-midi.gura"
cases="$cases test-module.gura"
cases="$cases test-object.gura"
cases="$cases test-opengl.gura"
cases="$cases test-operator.gura"
cases="$cases test-optimize.gura"
cases="$cases test-path.gura"
cases="$cases test-re.gura"
cases="$cases test-repeater.gura"
cases="$cases test-sqlite3.gura"
cases="$cases test-stream.gura"
cases="$cases test-string.gura"
cases="$cases test-template.gura"
cases="$cases test-value.gura"
cases="$cases test-xml.gura"
cases="$cases test-xhtml.gura"
cases="$cases test-yaml.gura"

if [ "$1" = "" ]; then
	for case in $cases
	do
		echo $case
		gura test-$case.gura > result/test-$case.result.txt
		diff -u --strip-trailing-cr result/test-$case.sample.txt result/test-$case.result.txt
	done	
elif [ "$1" = "genscript" ]; then
	for case in $cases
	do
		echo $case
		gura genscript.gura --eval test-$case.gura > result/test-$case.result.txt
		diff -u --strip-trailing-cr result/test-$case.sample.txt result/test-$case.result.txt
	done	
elif [ "$1" = "update" ]; then
	for case in $cases
	do
		echo $case
		gura test-$case.gura > result/test-$case.sample.txt
	done	
else
	case="$1"
	echo $case
	gura test-$case.gura > result/test-$case.result.txt
	diff -u --strip-trailing-cr result/test-$case.sample.txt result/test-$case.result.txt
fi
