#!/usr/bin/osascript

on run argv
  set dirCurrent to POSIX path of ((path to me as text) & "::")
  set dirResources to dirCurrent & "../Resources/"
  set pathGura to dirResources & "bin/gura"
  tell application "Terminal"
    activate
    do script "clear;\"" & pathGura & "\" -t -i macsetup"
  end
end run
