#ifndef __STDAFX_H__
#define __STDAFX_H__

#include "Module_cairo.h"
#include "Object_context.h"
#include "Object_font_extents.h"
#include "Object_text_extents.h"
#include "Object_rectangle.h"
#include "Object_rectangle_int.h"
#include "Object_region.h"
#include "Object_font_face.h"
#include "Object_toy_font_face.h"
#include "Object_ft_font_face.h"
#include "Object_win32_font_face.h"
#include "Object_quartz_font_face.h"
#include "Object_user_font_face.h"
#include "Object_scaled_font.h"
#include "Object_font_options.h"
#include "Object_device.h"
#include "Object_surface.h"
#include "Object_image_surface.h"
#include "Object_Writer_surface.h"
#include "Object_pdf_surface.h"
#include "Object_ps_surface.h"
#include "Object_recording_surface.h"
#include "Object_win32_surface.h"
#include "Object_svg_surface.h"
#include "Object_quartz_surface.h"
#include "Object_xcb_surface.h"
#include "Object_xlib_surface.h"
#include "Object_script_surface.h"
#include "Object_pattern.h"
#include "Object_path.h"
#include "Object_glyph.h"
#include "Object_text_cluster.h"

#endif
