//=============================================================================
// Command.cpp
//=============================================================================
#include "stdafx.h"

Gura_BeginModuleScope(doxygen)

//-----------------------------------------------------------------------------
// ArgOwner
//-----------------------------------------------------------------------------
ArgOwner::~ArgOwner()
{
	Clear();
}

void ArgOwner::Clear()
{
	foreach (ArgOwner, ppArg, *this) {
		delete *ppArg;
	}
	clear();
}

//-----------------------------------------------------------------------------
// Command
//-----------------------------------------------------------------------------
void Command::Initialize()
{
	const bool Optional = true;
	static const Command *dcommands[] = {
		// Structural indicators
		new Command("addtogroup",
					new ArgWord("name"),
					new ArgLine("title", Optional)),
		new Command("callgraph"),
		new Command("hidecallgrph"),
		new Command("callergraph"),
		new Command("hidecallergraph"),
		new Command("category",
					new ArgWord("name"),
					new ArgWord("header_file", Optional),
					new ArgWord("header_name", Optional)),
		new Command("class",
					new ArgWord("name"),
					new ArgWord("header_file", Optional),
					new ArgWord("header_name", Optional)),
		new Command("def",
					new ArgWord("name")),
		new Command("defgroup",
					new ArgWord("name"),
					new ArgLine("group_title")),
		new Command("dir",
					new ArgWord("path_fragment", Optional)),
		new Command("enum",
					new ArgWord("name")),
		new Command("example",
					new ArgWord("file_name")),
		new Command("endinternal"),
		new Command("extends",
					new ArgWord("name")),
		new Command("file",
					new ArgWord("name", Optional)),
		new Command("fn",
					new ArgLine("function_declaration")),
		new Command("headerfile",
					new ArgWord("header_file"),
					new ArgWord("hewder_name", Optional)),
		new Command("hideinitializer"),
		new Command("idlexcept",
					new ArgWord("name")),
		new Command("implements",
					new ArgWord("name")),
		new Command("ingroup",
					new ArgWord("groupname")),
		new Command("interface",
					new ArgWord("name"),
					new ArgWord("header_file", Optional),
					new ArgWord("header_name", Optional)),
		new Command("internal"),
		new Command("mainpage",
					new ArgLine("title", Optional)),
		new Command("memberof",
					new ArgWord("name")),
		new Command("name",
					new ArgLine("header", Optional)),
		new Command("namespace",
					new ArgWord("name")),
		new Command("nosubgrouping"),
		new Command("overload"),
		new Command("package"),
		new Command("page"),
		new Command("private"),
		new Command("privatesection"),
		new Command("property"),
		new Command("protected"),
		new Command("protectedsection"),
		new Command("protocol"),
		new Command("public"),
		new Command("publicsection"),
		new Command("pure"),
		new Command("relates"),
		new Command("related"),
		new Command("relatedalso"),
		new Command("showinitializer"),
		new Command("static"),
		new Command("struct"),
		new Command("typedef"),
		new Command("union"),
		new Command("var"),
		new Command("vhdlflow"),
		new Command("weakgroup"),
		// Section indicators
		new Command("attention"),
		new Command("author"),
		new Command("authors"),
		new Command("brief"),
		new Command("bug"),
		new Command("cond"),
		new Command("copyright"),
		new Command("date"),
		new Command("deprecated"),
		new Command("details"),
		new Command("else"),
		new Command("elseif"),
		new Command("endcond"),
		new Command("endif"),
		new Command("exception"),
		new Command("if"),
		new Command("ifnot"),
		new Command("invariant"),
		new Command("note"),
		new Command("par"),
		new Command("param"),
		new Command("parblock"),
		new Command("endparblock"),
		new Command("tparam"),
		new Command("post"),
		new Command("pre"),
		new Command("remark"),
		new Command("remarks"),
		new Command("result"),
		new Command("return"),
		new Command("returns"),
		new Command("retval"),
		new Command("sa"),
		new Command("see"),
		new Command("short"),
		new Command("since"),
		new Command("test"),
		new Command("throw"),
		new Command("throws"),
		new Command("todo"),
		new Command("version"),
		new Command("warning"),
		new Command("xrefitem"),
		// Commands to create links
		new Command("addindex"),
		new Command("anchor"),
		new Command("cite"),
		new Command("endlink"),
		new Command("link"),
		new Command("ref"),
		new Command("refitem"),
		new Command("secreflist"),
		new Command("endsecreflist"),
		new Command("subpage"),
		new Command("tableofcontents"),
		new Command("section"),
		new Command("subsection"),
		new Command("subsubsection"),
		new Command("paragrph"),
		// Commands for displaying examples
		new Command("dontinclude"),
		new Command("include"),
		new Command("includelineno"),
		new Command("line"),
		new Command("skip"),
		new Command("skipline"),
		new Command("snippet"),
		new Command("until"),
		new Command("verbinclude"),
		new Command("htmlinclude"),
		new Command("latexinclude"),
		// Commands for visual enhancements
		new Command("a"),
		new Command("arg"),
		new Command("b"),
		new Command("c"),
		new Command("code"),
		new Command("copydoc"),
		new Command("copybrief"),
		new Command("copydetails"),
		new Command("docbookonly"),
		new Command("dot"),
		new Command("msc"),
		new Command("startuml"),
		new Command("dotfile"),
		new Command("diafile"),
		new Command("e"),
		new Command("em"),
		new Command("endcode"),
		new Command("endcodebookonly"),
		new Command("enddot"),
		new Command("enduml"),
		new Command("endhtmlonly"),
		new Command("endlatexonly"),
		new Command("endmanonly"),
		new Command("endrtfonly"),
		new Command("endverbatim"),
		new Command("endxmlonly"),
		new Command("f$"),
		new Command("f["),
		new Command("f]"),
		new Command("f}"),
		new Command("htmlonly"),
		new Command("image"),
		new Command("latexonly"),
		new Command("manonly"),
		new Command("li"),
		new Command("n"),
		new Command("p"),
		new Command("rtfonly"),
		new Command("verbatim"),
		new Command("xmlonly"),
		new Command("\\"),
		new Command("\\@"),
		new Command("&"),
		new Command("$"),
		new Command("#"),
		new Command("<"),
		new Command(">"),
		new Command("%"),
		new Command("\""),
		new Command("."),
		new Command("::"),
		new Command("|"),
		new Command("--"),
		new Command("---"),
	};
};
	
Gura_EndModuleScope(doxygen)
