//=============================================================================
// DCommands.cpp
//=============================================================================
#include "stdafx.h"

Gura_BeginModuleScope(doxygen)

//-----------------------------------------------------------------------------
// DArgOwner
//-----------------------------------------------------------------------------
DArgOwner::~DArgOwner()
{
	Clear();
}

void DArgOwner::Clear()
{
	foreach (DArgOwner, ppDArg, *this) {
		delete *ppDArg;
	}
	clear();
}

//-----------------------------------------------------------------------------
// DCommand
//-----------------------------------------------------------------------------
void DCommand::Initialize()
{
	const bool Optional = true;
	static const DCommand *dcommands[] = {
		// Structural indicators
		new DCommand("addtogroup",
					 new DArgWord("name"),
					 new DArgLine("title", Optional)),
		new DCommand("callgraph"),
		new DCommand("hidecallgrph"),
		new DCommand("callergraph"),
		new DCommand("hidecallergraph"),
		new DCommand("category",
					 new DArgWord("name"),
					 new DArgWord("header_file", Optional),
					 new DArgWord("header_name", Optional)),
		new DCommand("class",
					 new DArgWord("name"),
					 new DArgWord("header_file", Optional),
					 new DArgWord("header_name", Optional)),
		new DCommand("def",
					 new DArgWord("name")),
		new DCommand("defgroup",
					 new DArgWord("name"),
					 new DArgLine("group_title")),
		new DCommand("dir",
					 new DArgWord("path_fragment", Optional)),
		new DCommand("enum",
					 new DArgWord("name")),
		new DCommand("example",
					 new DArgWord("file_name")),
		new DCommand("endinternal"),
		new DCommand("extends",
					 new DArgWord("name")),
		new DCommand("file",
					 new DArgWord("name", Optional)),
		new DCommand("fn",
					 new DArgLine("function_declaration")),
		new DCommand("headerfile",
					 new DArgWord("header_file"),
					 new DArgWord("hewder_name", Optional)),
		new DCommand("hideinitializer"),
		new DCommand("idlexcept",
					 new DArgWord("name")),
		new DCommand("implements",
					 new DArgWord("name")),
		new DCommand("ingroup",
					 new DArgWord("groupname")),
		new DCommand("interface",
					 new DArgWord("name"),
					 new DArgWord("header_file", Optional),
					 new DArgWord("header_name", Optional)),
		new DCommand("internal"),
		new DCommand("mainpage",
					 new DArgLine("title", Optional)),
		new DCommand("memberof",
					 new DArgWord("name")),
		new DCommand("name",
					 new DArgLine("header", Optional)),
		new DCommand("namespace",
					 new DArgWord("name")),
		new DCommand("nosubgrouping"),
		new DCommand("overload"),
		new DCommand("package"),
		new DCommand("page"),
		new DCommand("private"),
		new DCommand("privatesection"),
		new DCommand("property"),
		new DCommand("protected"),
		new DCommand("protectedsection"),
		new DCommand("protocol"),
		new DCommand("public"),
		new DCommand("publicsection"),
		new DCommand("pure"),
		new DCommand("relates"),
		new DCommand("related"),
		new DCommand("relatedalso"),
		new DCommand("showinitializer"),
		new DCommand("static"),
		new DCommand("struct"),
		new DCommand("typedef"),
		new DCommand("union"),
		new DCommand("var"),
		new DCommand("vhdlflow"),
		new DCommand("weakgroup"),
		// Section indicators
		new DCommand("attention"),
		new DCommand("author"),
		new DCommand("authors"),
		new DCommand("brief"),
		new DCommand("bug"),
		new DCommand("cond"),
		new DCommand("copyright"),
		new DCommand("date"),
		new DCommand("deprecated"),
		new DCommand("details"),
		new DCommand("else"),
		new DCommand("elseif"),
		new DCommand("endcond"),
		new DCommand("endif"),
		new DCommand("exception"),
		new DCommand("if"),
		new DCommand("ifnot"),
		new DCommand("invariant"),
		new DCommand("note"),
		new DCommand("par"),
		new DCommand("param"),
		new DCommand("parblock"),
		new DCommand("endparblock"),
		new DCommand("tparam"),
		new DCommand("post"),
		new DCommand("pre"),
		new DCommand("remark"),
		new DCommand("remarks"),
		new DCommand("result"),
		new DCommand("return"),
		new DCommand("returns"),
		new DCommand("retval"),
		new DCommand("sa"),
		new DCommand("see"),
		new DCommand("short"),
		new DCommand("since"),
		new DCommand("test"),
		new DCommand("throw"),
		new DCommand("throws"),
		new DCommand("todo"),
		new DCommand("version"),
		new DCommand("warning"),
		new DCommand("xrefitem"),
		// Commands to create links
		new DCommand("addindex"),
		new DCommand("anchor"),
		new DCommand("cite"),
		new DCommand("endlink"),
		new DCommand("link"),
		new DCommand("ref"),
		new DCommand("refitem"),
		new DCommand("secreflist"),
		new DCommand("endsecreflist"),
		new DCommand("subpage"),
		new DCommand("tableofcontents"),
		new DCommand("section"),
		new DCommand("subsection"),
		new DCommand("subsubsection"),
		new DCommand("paragrph"),
		// Commands for displaying examples
		new DCommand("dontinclude"),
		new DCommand("include"),
		new DCommand("includelineno"),
		new DCommand("line"),
		new DCommand("skip"),
		new DCommand("skipline"),
		new DCommand("snippet"),
		new DCommand("until"),
		new DCommand("verbinclude"),
		new DCommand("htmlinclude"),
		new DCommand("latexinclude"),
		// Commands for visual enhancements
		new DCommand("a"),
		new DCommand("arg"),
		new DCommand("b"),
		new DCommand("c"),
		new DCommand("code"),
		new DCommand("copydoc"),
		new DCommand("copybrief"),
		new DCommand("copydetails"),
		new DCommand("docbookonly"),
		new DCommand("dot"),
		new DCommand("msc"),
		new DCommand("startuml"),
		new DCommand("dotfile"),
		new DCommand("diafile"),
		new DCommand("e"),
		new DCommand("em"),
		new DCommand("endcode"),
		new DCommand("endcodebookonly"),
		new DCommand("enddot"),
		new DCommand("enduml"),
		new DCommand("endhtmlonly"),
		new DCommand("endlatexonly"),
		new DCommand("endmanonly"),
		new DCommand("endrtfonly"),
		new DCommand("endverbatim"),
		new DCommand("endxmlonly"),
		new DCommand("f$"),
		new DCommand("f["),
		new DCommand("f]"),
		new DCommand("f}"),
		new DCommand("htmlonly"),
		new DCommand("image"),
		new DCommand("latexonly"),
		new DCommand("manonly"),
		new DCommand("li"),
		new DCommand("n"),
		new DCommand("p"),
		new DCommand("rtfonly"),
		new DCommand("verbatim"),
		new DCommand("xmlonly"),
		new DCommand("\\"),
		new DCommand("\\@"),
		new DCommand("&"),
		new DCommand("$"),
		new DCommand("#"),
		new DCommand("<"),
		new DCommand(">"),
		new DCommand("%"),
		new DCommand("\""),
		new DCommand("."),
		new DCommand("::"),
		new DCommand("|"),
		new DCommand("--"),
		new DCommand("---"),
	};
};
	
Gura_EndModuleScope(doxygen)
