//----------------------------------------------------------------------------
// wxStyledTextCtrl
//----------------------------------------------------------------------------
#include "stdafx.h"

Gura_BeginModuleScope(wx)

//----------------------------------------------------------------------------
// Class derivation
//----------------------------------------------------------------------------
class wx_StyledTextCtrl: public wxStyledTextCtrl, public GuraObjectObserver {
private:
	Gura::Signal _sig;
	Object_wx_StyledTextCtrl *_pObj;
public:
	inline wx_StyledTextCtrl() : wxStyledTextCtrl(), _sig(NULL), _pObj(NULL) {}
	inline wx_StyledTextCtrl(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style, const wxString& name) : wxStyledTextCtrl(parent, id, pos, size, style, name), _sig(NULL), _pObj(NULL) {}
	~wx_StyledTextCtrl();
	inline void AssocWithGura(Gura::Signal &sig, Object_wx_StyledTextCtrl *pObj) {
		_sig = sig, _pObj = pObj;
	}
	// virtual function of GuraObjectObserver
	virtual void GuraObjectDeleted();
};

wx_StyledTextCtrl::~wx_StyledTextCtrl()
{
	if (_pObj != NULL) _pObj->InvalidateEntity();
}

void wx_StyledTextCtrl::GuraObjectDeleted()
{
	_pObj = NULL;
}

//----------------------------------------------------------------------------
// Implementation of functions
//----------------------------------------------------------------------------
Gura_DeclareFunction(StyledTextCtrlEmpty)
{
	SetMode(RSLTMODE_Normal, FLAG_None);
	SetClassToConstruct(Gura_UserClass(wx_StyledTextCtrl));
	DeclareBlock(OCCUR_ZeroOrOnce);
}

Gura_ImplementFunction(StyledTextCtrlEmpty)
{
	if (!CheckWxReady(sig)) return Value::Null;
	wx_StyledTextCtrl *pEntity = new wx_StyledTextCtrl();
	Object_wx_StyledTextCtrl *pObj = Object_wx_StyledTextCtrl::GetThisObj(args);
	if (pObj == NULL) {
		pObj = new Object_wx_StyledTextCtrl(pEntity, pEntity, OwnerFalse);
		pEntity->AssocWithGura(sig, pObj);
		return ReturnValue(env, sig, args, Value(pObj));
	}
	pObj->SetEntity(pEntity, pEntity, OwnerFalse);
	pEntity->AssocWithGura(sig, pObj);
	return ReturnValue(env, sig, args, args.GetThis());
}

Gura_DeclareFunction(StyledTextCtrl)
{
	SetMode(RSLTMODE_Normal, FLAG_Map);
	SetClassToConstruct(Gura_UserClass(wx_StyledTextCtrl));
	DeclareArg(env, "parent", VTYPE_wx_Window, OCCUR_Once);
	DeclareArg(env, "id", VTYPE_number, OCCUR_Once);
	DeclareArg(env, "pos", VTYPE_wx_Point, OCCUR_ZeroOrOnce);
	DeclareArg(env, "size", VTYPE_wx_Size, OCCUR_ZeroOrOnce);
	DeclareArg(env, "style", VTYPE_number, OCCUR_ZeroOrOnce);
	DeclareArg(env, "name", VTYPE_string, OCCUR_ZeroOrOnce);
	DeclareBlock(OCCUR_ZeroOrOnce);
}

Gura_ImplementFunction(StyledTextCtrl)
{
	if (!CheckWxReady(sig)) return Value::Null;
	wxWindow *parent = Object_wx_Window::GetObject(args, 0)->GetEntity();
	wxWindowID id = static_cast<wxWindowID>(args.GetInt(1));
	wxPoint *pos = (wxPoint *)(&wxDefaultPosition);
	if (args.IsValid(2)) pos = Object_wx_Point::GetObject(args, 2)->GetEntity();
	wxSize *size = (wxSize *)(&wxDefaultSize);
	if (args.IsValid(3)) size = Object_wx_Size::GetObject(args, 3)->GetEntity();
	long style = 0;
	if (args.IsValid(4)) style = args.GetLong(4);
	wxString name = wxSTCNameStr;
	if (args.IsValid(5)) name = wxString::FromUTF8(args.GetString(5));
	wx_StyledTextCtrl *pEntity = new wx_StyledTextCtrl(parent, id, *pos, *size, style, name);

	pEntity->SetWrapIndentMode(wxSTC_WRAPINDENT_SAME);

	Object_wx_StyledTextCtrl *pObj = Object_wx_StyledTextCtrl::GetThisObj(args);
	if (pObj == NULL) {
		pObj = new Object_wx_StyledTextCtrl(pEntity, pEntity, OwnerFalse);
		pEntity->AssocWithGura(sig, pObj);
		return ReturnValue(env, sig, args, Value(pObj));
	}
	pObj->SetEntity(pEntity, pEntity, OwnerFalse);
	pEntity->AssocWithGura(sig, pObj);
	return ReturnValue(env, sig, args, args.GetThis());
}

//----------------------------------------------------------------------------
// Object_wxStyledTextCtrl
//----------------------------------------------------------------------------
Object_wx_StyledTextCtrl::~Object_wx_StyledTextCtrl()
{
}

Object *Object_wx_StyledTextCtrl::Clone() const
{
	return NULL;
}

String Object_wx_StyledTextCtrl::ToString(bool exprFlag)
{
	String rtn("<wx.StyledTextCtrl:");
	if (GetEntity() == NULL) {
		rtn += "invalid>";
	} else {
		char buff[64];
		::sprintf(buff, "%p>", GetEntity());
		rtn += buff;
	}
	return rtn;
}

//----------------------------------------------------------------------------
// Implementation of methods
//----------------------------------------------------------------------------
Gura_DeclareMethod(wx_StyledTextCtrl, AddText)
{
	SetMode(RSLTMODE_Void, FLAG_None);
	DeclareArg(env, "text",	VTYPE_string, OCCUR_Once);
}

Gura_ImplementMethod(wx_StyledTextCtrl, AddText)
{
	Object_wx_StyledTextCtrl *pThis = Object_wx_StyledTextCtrl::GetThisObj(args);
	if (pThis->IsInvalid(sig)) return Value::Null;
	wxString text = wxString::FromUTF8(args.GetString(0));
	pThis->GetEntity()->AddText(text);
	return Value::Null;
}

Gura_DeclareMethod(wx_StyledTextCtrl, AddStyledText)
{
	SetMode(RSLTMODE_Void, FLAG_None);
	DeclareArg(env, "data",	VTYPE_wx_MemoryBuffer, OCCUR_Once);
}

Gura_ImplementMethod(wx_StyledTextCtrl, AddStyledText)
{
	Object_wx_StyledTextCtrl *pThis = Object_wx_StyledTextCtrl::GetThisObj(args);
	if (pThis->IsInvalid(sig)) return Value::Null;
	wxMemoryBuffer *data = Object_wx_MemoryBuffer::GetObject(args, 0)->GetEntity();
	pThis->GetEntity()->AddStyledText(*data);
	return Value::Null;
}

Gura_DeclareMethod(wx_StyledTextCtrl, InsertText)
{
	SetMode(RSLTMODE_Void, FLAG_None);
	DeclareArg(env, "pos",	VTYPE_number, OCCUR_Once);
	DeclareArg(env, "text",	VTYPE_string, OCCUR_Once);
}

Gura_ImplementMethod(wx_StyledTextCtrl, InsertText)
{
	Object_wx_StyledTextCtrl *pThis = Object_wx_StyledTextCtrl::GetThisObj(args);
	if (pThis->IsInvalid(sig)) return Value::Null;
	int pos = args.GetInt(0);
	wxString text = wxString::FromUTF8(args.GetString(1));
	pThis->GetEntity()->InsertText(pos, text);
	return Value::Null;
}

Gura_DeclareMethod(wx_StyledTextCtrl, ClearAll)
{
	SetMode(RSLTMODE_Void, FLAG_None);
}

Gura_ImplementMethod(wx_StyledTextCtrl, ClearAll)
{
	Object_wx_StyledTextCtrl *pThis = Object_wx_StyledTextCtrl::GetThisObj(args);
	if (pThis->IsInvalid(sig)) return Value::Null;
	pThis->GetEntity()->ClearAll();
	return Value::Null;
}

Gura_DeclareMethod(wx_StyledTextCtrl, DeleteRange)
{
	SetMode(RSLTMODE_Void, FLAG_None);
	DeclareArg(env, "pos",			VTYPE_number, OCCUR_Once);
	DeclareArg(env, "deleteLength",	VTYPE_number, OCCUR_Once);
}

Gura_ImplementMethod(wx_StyledTextCtrl, DeleteRange)
{
	Object_wx_StyledTextCtrl *pThis = Object_wx_StyledTextCtrl::GetThisObj(args);
	if (pThis->IsInvalid(sig)) return Value::Null;
	int pos = args.GetInt(0);
	int deleteLength = args.GetInt(1);
	pThis->GetEntity()->DeleteRange(pos, deleteLength);
	return Value::Null;
}

Gura_DeclareMethod(wx_StyledTextCtrl, ClearDocumentStyle)
{
	SetMode(RSLTMODE_Void, FLAG_None);
}

Gura_ImplementMethod(wx_StyledTextCtrl, ClearDocumentStyle)
{
	Object_wx_StyledTextCtrl *pThis = Object_wx_StyledTextCtrl::GetThisObj(args);
	if (pThis->IsInvalid(sig)) return Value::Null;
	pThis->GetEntity()->ClearDocumentStyle();
	return Value::Null;
}

Gura_DeclareMethod(wx_StyledTextCtrl, GetLength)
{
	SetMode(RSLTMODE_Normal, FLAG_None);
}

Gura_ImplementMethod(wx_StyledTextCtrl, GetLength)
{
	Object_wx_StyledTextCtrl *pThis = Object_wx_StyledTextCtrl::GetThisObj(args);
	if (pThis->IsInvalid(sig)) return Value::Null;
	int rtn = pThis->GetEntity()->GetLength();
	return ReturnValue(env, sig, args, Value(rtn));
}

Gura_DeclareMethod(wx_StyledTextCtrl, GetCharAt)
{
	SetMode(RSLTMODE_Normal, FLAG_None);
	DeclareArg(env, "pos",	VTYPE_number, OCCUR_Once);
}

Gura_ImplementMethod(wx_StyledTextCtrl, GetCharAt)
{
	Object_wx_StyledTextCtrl *pThis = Object_wx_StyledTextCtrl::GetThisObj(args);
	if (pThis->IsInvalid(sig)) return Value::Null;
	int pos = args.GetInt(0);
	int rtn = pThis->GetEntity()->GetCharAt(pos);
	return ReturnValue(env, sig, args, Value(rtn));
}

Gura_DeclareMethod(wx_StyledTextCtrl, GetCurrentPos)
{
	SetMode(RSLTMODE_Normal, FLAG_None);
}

Gura_ImplementMethod(wx_StyledTextCtrl, GetCurrentPos)
{
	Object_wx_StyledTextCtrl *pThis = Object_wx_StyledTextCtrl::GetThisObj(args);
	if (pThis->IsInvalid(sig)) return Value::Null;
	int rtn = pThis->GetEntity()->GetCurrentPos();
	return ReturnValue(env, sig, args, Value(rtn));
}

Gura_DeclareMethod(wx_StyledTextCtrl, GetAnchor)
{
	SetMode(RSLTMODE_Normal, FLAG_None);
}

Gura_ImplementMethod(wx_StyledTextCtrl, GetAnchor)
{
	Object_wx_StyledTextCtrl *pThis = Object_wx_StyledTextCtrl::GetThisObj(args);
	if (pThis->IsInvalid(sig)) return Value::Null;
	int rtn = pThis->GetEntity()->GetAnchor();
	return ReturnValue(env, sig, args, Value(rtn));
}

Gura_DeclareMethod(wx_StyledTextCtrl, GetStyleAt)
{
	SetMode(RSLTMODE_Normal, FLAG_None);
	DeclareArg(env, "pos",	VTYPE_number, OCCUR_Once);
}

Gura_ImplementMethod(wx_StyledTextCtrl, GetStyleAt)
{
	Object_wx_StyledTextCtrl *pThis = Object_wx_StyledTextCtrl::GetThisObj(args);
	if (pThis->IsInvalid(sig)) return Value::Null;
	int pos = args.GetInt(0);
	int rtn = pThis->GetEntity()->GetStyleAt(pos);
	return ReturnValue(env, sig, args, Value(rtn));
}

Gura_DeclareMethod(wx_StyledTextCtrl, Redo)
{
	SetMode(RSLTMODE_Void, FLAG_None);
}

Gura_ImplementMethod(wx_StyledTextCtrl, Redo)
{
	Object_wx_StyledTextCtrl *pThis = Object_wx_StyledTextCtrl::GetThisObj(args);
	if (pThis->IsInvalid(sig)) return Value::Null;
	pThis->GetEntity()->Redo();
	return Value::Null;
}

//----------------------------------------------------------------------------
// Implementation of class
//----------------------------------------------------------------------------
Gura_ImplementUserInheritableClass(wx_StyledTextCtrl)
{
	// assignment of values
	Gura_AssignWxValue(STC_INVALID_POSITION);
	Gura_AssignWxValue(STC_START);
	Gura_AssignWxValue(STC_OPTIONAL_START);
	Gura_AssignWxValue(STC_LEXER_START);
	Gura_AssignWxValue(STC_WS_INVISIBLE);
	Gura_AssignWxValue(STC_WS_VISIBLEALWAYS);
	Gura_AssignWxValue(STC_WS_VISIBLEAFTERINDENT);
	Gura_AssignWxValue(STC_EOL_CRLF);
	Gura_AssignWxValue(STC_EOL_CR);
	Gura_AssignWxValue(STC_EOL_LF);
	Gura_AssignWxValue(STC_CP_UTF8);
	Gura_AssignWxValue(STC_MARKER_MAX);
	Gura_AssignWxValue(STC_MARK_CIRCLE);
	Gura_AssignWxValue(STC_MARK_ROUNDRECT);
	Gura_AssignWxValue(STC_MARK_ARROW);
	Gura_AssignWxValue(STC_MARK_SMALLRECT);
	Gura_AssignWxValue(STC_MARK_SHORTARROW);
	Gura_AssignWxValue(STC_MARK_EMPTY);
	Gura_AssignWxValue(STC_MARK_ARROWDOWN);
	Gura_AssignWxValue(STC_MARK_MINUS);
	Gura_AssignWxValue(STC_MARK_PLUS);
	Gura_AssignWxValue(STC_MARK_VLINE);
	Gura_AssignWxValue(STC_MARK_LCORNER);
	Gura_AssignWxValue(STC_MARK_TCORNER);
	Gura_AssignWxValue(STC_MARK_BOXPLUS);
	Gura_AssignWxValue(STC_MARK_BOXPLUSCONNECTED);
	Gura_AssignWxValue(STC_MARK_BOXMINUS);
	Gura_AssignWxValue(STC_MARK_BOXMINUSCONNECTED);
	Gura_AssignWxValue(STC_MARK_LCORNERCURVE);
	Gura_AssignWxValue(STC_MARK_TCORNERCURVE);
	Gura_AssignWxValue(STC_MARK_CIRCLEPLUS);
	Gura_AssignWxValue(STC_MARK_CIRCLEPLUSCONNECTED);
	Gura_AssignWxValue(STC_MARK_CIRCLEMINUS);
	Gura_AssignWxValue(STC_MARK_CIRCLEMINUSCONNECTED);
	Gura_AssignWxValue(STC_MARK_BACKGROUND);
	Gura_AssignWxValue(STC_MARK_DOTDOTDOT);
	Gura_AssignWxValue(STC_MARK_ARROWS);
	Gura_AssignWxValue(STC_MARK_PIXMAP);
	Gura_AssignWxValue(STC_MARK_FULLRECT);
	Gura_AssignWxValue(STC_MARK_LEFTRECT);
	Gura_AssignWxValue(STC_MARK_AVAILABLE);
	Gura_AssignWxValue(STC_MARK_UNDERLINE);
	Gura_AssignWxValue(STC_MARK_RGBAIMAGE);
	Gura_AssignWxValue(STC_MARK_CHARACTER);
	Gura_AssignWxValue(STC_MARKNUM_FOLDEREND);
	Gura_AssignWxValue(STC_MARKNUM_FOLDEROPENMID);
	Gura_AssignWxValue(STC_MARKNUM_FOLDERMIDTAIL);
	Gura_AssignWxValue(STC_MARKNUM_FOLDERTAIL);
	Gura_AssignWxValue(STC_MARKNUM_FOLDERSUB);
	Gura_AssignWxValue(STC_MARKNUM_FOLDER);
	Gura_AssignWxValue(STC_MARKNUM_FOLDEROPEN);
	Gura_AssignWxValue(STC_MASK_FOLDERS);
	Gura_AssignWxValue(STC_MARGIN_SYMBOL);
	Gura_AssignWxValue(STC_MARGIN_NUMBER);
	Gura_AssignWxValue(STC_MARGIN_BACK);
	Gura_AssignWxValue(STC_MARGIN_FORE);
	Gura_AssignWxValue(STC_MARGIN_TEXT);
	Gura_AssignWxValue(STC_MARGIN_RTEXT);
	Gura_AssignWxValue(STC_STYLE_DEFAULT);
	Gura_AssignWxValue(STC_STYLE_LINENUMBER);
	Gura_AssignWxValue(STC_STYLE_BRACELIGHT);
	Gura_AssignWxValue(STC_STYLE_BRACEBAD);
	Gura_AssignWxValue(STC_STYLE_CONTROLCHAR);
	Gura_AssignWxValue(STC_STYLE_INDENTGUIDE);
	Gura_AssignWxValue(STC_STYLE_CALLTIP);
	Gura_AssignWxValue(STC_STYLE_LASTPREDEFINED);
	Gura_AssignWxValue(STC_STYLE_MAX);
	Gura_AssignWxValue(STC_CHARSET_ANSI);
	Gura_AssignWxValue(STC_CHARSET_DEFAULT);
	Gura_AssignWxValue(STC_CHARSET_BALTIC);
	Gura_AssignWxValue(STC_CHARSET_CHINESEBIG5);
	Gura_AssignWxValue(STC_CHARSET_EASTEUROPE);
	Gura_AssignWxValue(STC_CHARSET_GB2312);
	Gura_AssignWxValue(STC_CHARSET_GREEK);
	Gura_AssignWxValue(STC_CHARSET_HANGUL);
	Gura_AssignWxValue(STC_CHARSET_MAC);
	Gura_AssignWxValue(STC_CHARSET_OEM);
	Gura_AssignWxValue(STC_CHARSET_RUSSIAN);
	Gura_AssignWxValue(STC_CHARSET_CYRILLIC);
	Gura_AssignWxValue(STC_CHARSET_SHIFTJIS);
	Gura_AssignWxValue(STC_CHARSET_SYMBOL);
	Gura_AssignWxValue(STC_CHARSET_TURKISH);
	Gura_AssignWxValue(STC_CHARSET_JOHAB);
	Gura_AssignWxValue(STC_CHARSET_HEBREW);
	Gura_AssignWxValue(STC_CHARSET_ARABIC);
	Gura_AssignWxValue(STC_CHARSET_VIETNAMESE);
	Gura_AssignWxValue(STC_CHARSET_THAI);
	Gura_AssignWxValue(STC_CHARSET_8859_15);
	Gura_AssignWxValue(STC_CASE_MIXED);
	Gura_AssignWxValue(STC_CASE_UPPER);
	Gura_AssignWxValue(STC_CASE_LOWER);
	Gura_AssignWxValue(STC_FONT_SIZE_MULTIPLIER);
	Gura_AssignWxValue(STC_WEIGHT_NORMAL);
	Gura_AssignWxValue(STC_WEIGHT_SEMIBOLD);
	Gura_AssignWxValue(STC_WEIGHT_BOLD);
	Gura_AssignWxValue(STC_INDIC_PLAIN);
	Gura_AssignWxValue(STC_INDIC_SQUIGGLE);
	Gura_AssignWxValue(STC_INDIC_TT);
	Gura_AssignWxValue(STC_INDIC_DIAGONAL);
	Gura_AssignWxValue(STC_INDIC_STRIKE);
	Gura_AssignWxValue(STC_INDIC_HIDDEN);
	Gura_AssignWxValue(STC_INDIC_BOX);
	Gura_AssignWxValue(STC_INDIC_ROUNDBOX);
	Gura_AssignWxValue(STC_INDIC_STRAIGHTBOX);
	Gura_AssignWxValue(STC_INDIC_DASH);
	Gura_AssignWxValue(STC_INDIC_DOTS);
	Gura_AssignWxValue(STC_INDIC_SQUIGGLELOW);
	Gura_AssignWxValue(STC_INDIC_DOTBOX);
	Gura_AssignWxValue(STC_INDIC_MAX);
	Gura_AssignWxValue(STC_INDIC_CONTAINER);
	Gura_AssignWxValue(STC_INDIC0_MASK);
	Gura_AssignWxValue(STC_INDIC1_MASK);
	Gura_AssignWxValue(STC_INDIC2_MASK);
	Gura_AssignWxValue(STC_INDICS_MASK);
	Gura_AssignWxValue(STC_IV_NONE);
	Gura_AssignWxValue(STC_IV_REAL);
	Gura_AssignWxValue(STC_IV_LOOKFORWARD);
	Gura_AssignWxValue(STC_IV_LOOKBOTH);
	Gura_AssignWxValue(STC_PRINT_NORMAL);
	Gura_AssignWxValue(STC_PRINT_INVERTLIGHT);
	Gura_AssignWxValue(STC_PRINT_BLACKONWHITE);
	Gura_AssignWxValue(STC_PRINT_COLOURONWHITE);
	Gura_AssignWxValue(STC_PRINT_COLOURONWHITEDEFAULTBG);
	Gura_AssignWxValue(STC_FIND_WHOLEWORD);
	Gura_AssignWxValue(STC_FIND_MATCHCASE);
	Gura_AssignWxValue(STC_FIND_WORDSTART);
	Gura_AssignWxValue(STC_FIND_REGEXP);
	Gura_AssignWxValue(STC_FIND_POSIX);
	Gura_AssignWxValue(STC_FOLDLEVELBASE);
	Gura_AssignWxValue(STC_FOLDLEVELWHITEFLAG);
	Gura_AssignWxValue(STC_FOLDLEVELHEADERFLAG);
	Gura_AssignWxValue(STC_FOLDLEVELNUMBERMASK);
	Gura_AssignWxValue(STC_FOLDFLAG_LINEBEFORE_EXPANDED);
	Gura_AssignWxValue(STC_FOLDFLAG_LINEBEFORE_CONTRACTED);
	Gura_AssignWxValue(STC_FOLDFLAG_LINEAFTER_EXPANDED);
	Gura_AssignWxValue(STC_FOLDFLAG_LINEAFTER_CONTRACTED);
	Gura_AssignWxValue(STC_FOLDFLAG_LEVELNUMBERS);
	Gura_AssignWxValue(STC_TIME_FOREVER);
	Gura_AssignWxValue(STC_WRAP_NONE);
	Gura_AssignWxValue(STC_WRAP_WORD);
	Gura_AssignWxValue(STC_WRAP_CHAR);
	Gura_AssignWxValue(STC_WRAPVISUALFLAG_NONE);
	Gura_AssignWxValue(STC_WRAPVISUALFLAG_END);
	Gura_AssignWxValue(STC_WRAPVISUALFLAG_START);
	Gura_AssignWxValue(STC_WRAPVISUALFLAG_MARGIN);
	Gura_AssignWxValue(STC_WRAPVISUALFLAGLOC_DEFAULT);
	Gura_AssignWxValue(STC_WRAPVISUALFLAGLOC_END_BY_TEXT);
	Gura_AssignWxValue(STC_WRAPVISUALFLAGLOC_START_BY_TEXT);
	Gura_AssignWxValue(STC_WRAPINDENT_FIXED);
	Gura_AssignWxValue(STC_WRAPINDENT_SAME);
	Gura_AssignWxValue(STC_WRAPINDENT_INDENT);
	Gura_AssignWxValue(STC_CACHE_NONE);
	Gura_AssignWxValue(STC_CACHE_CARET);
	Gura_AssignWxValue(STC_CACHE_PAGE);
	Gura_AssignWxValue(STC_CACHE_DOCUMENT);
	Gura_AssignWxValue(STC_EFF_QUALITY_MASK);
	Gura_AssignWxValue(STC_EFF_QUALITY_DEFAULT);
	Gura_AssignWxValue(STC_EFF_QUALITY_NON_ANTIALIASED);
	Gura_AssignWxValue(STC_EFF_QUALITY_ANTIALIASED);
	Gura_AssignWxValue(STC_EFF_QUALITY_LCD_OPTIMIZED);
	Gura_AssignWxValue(STC_MULTIPASTE_ONCE);
	Gura_AssignWxValue(STC_MULTIPASTE_EACH);
	Gura_AssignWxValue(STC_EDGE_NONE);
	Gura_AssignWxValue(STC_EDGE_LINE);
	Gura_AssignWxValue(STC_EDGE_BACKGROUND);
	Gura_AssignWxValue(STC_STATUS_OK);
	Gura_AssignWxValue(STC_STATUS_FAILURE);
	Gura_AssignWxValue(STC_STATUS_BADALLOC);
	Gura_AssignWxValue(STC_CURSORNORMAL);
	Gura_AssignWxValue(STC_CURSORARROW);
	Gura_AssignWxValue(STC_CURSORWAIT);
	Gura_AssignWxValue(STC_CURSORREVERSEARROW);
	Gura_AssignWxValue(STC_VISIBLE_SLOP);
	Gura_AssignWxValue(STC_VISIBLE_STRICT);
	Gura_AssignWxValue(STC_CARET_SLOP);
	Gura_AssignWxValue(STC_CARET_STRICT);
	Gura_AssignWxValue(STC_CARET_JUMPS);
	Gura_AssignWxValue(STC_CARET_EVEN);
	Gura_AssignWxValue(STC_SEL_STREAM);
	Gura_AssignWxValue(STC_SEL_RECTANGLE);
	Gura_AssignWxValue(STC_SEL_LINES);
	Gura_AssignWxValue(STC_SEL_THIN);
	Gura_AssignWxValue(STC_CASEINSENSITIVEBEHAVIOUR_RESPECTCASE);
	Gura_AssignWxValue(STC_CASEINSENSITIVEBEHAVIOUR_IGNORECASE);
	Gura_AssignWxValue(STC_CARETSTICKY_OFF);
	Gura_AssignWxValue(STC_CARETSTICKY_ON);
	Gura_AssignWxValue(STC_CARETSTICKY_WHITESPACE);
	Gura_AssignWxValue(STC_ALPHA_TRANSPARENT);
	Gura_AssignWxValue(STC_ALPHA_OPAQUE);
	Gura_AssignWxValue(STC_ALPHA_NOALPHA);
	Gura_AssignWxValue(STC_CARETSTYLE_INVISIBLE);
	Gura_AssignWxValue(STC_CARETSTYLE_LINE);
	Gura_AssignWxValue(STC_CARETSTYLE_BLOCK);
	Gura_AssignWxValue(STC_MARGINOPTION_NONE);
	Gura_AssignWxValue(STC_MARGINOPTION_SUBLINESELECT);
	Gura_AssignWxValue(STC_ANNOTATION_HIDDEN);
	Gura_AssignWxValue(STC_ANNOTATION_STANDARD);
	Gura_AssignWxValue(STC_ANNOTATION_BOXED);
	Gura_AssignWxValue(STC_UNDO_MAY_COALESCE);
	Gura_AssignWxValue(STC_SCVS_NONE);
	Gura_AssignWxValue(STC_SCVS_RECTANGULARSELECTION);
	Gura_AssignWxValue(STC_SCVS_USERACCESSIBLE);
	Gura_AssignWxValue(STC_TECHNOLOGY_DEFAULT);
	Gura_AssignWxValue(STC_TECHNOLOGY_DIRECTWRITE);
	Gura_AssignWxValue(STC_KEYWORDSET_MAX);
	Gura_AssignWxValue(STC_TYPE_BOOLEAN);
	Gura_AssignWxValue(STC_TYPE_INTEGER);
	Gura_AssignWxValue(STC_TYPE_STRING);
	Gura_AssignWxValue(STC_MOD_INSERTTEXT);
	Gura_AssignWxValue(STC_MOD_DELETETEXT);
	Gura_AssignWxValue(STC_MOD_CHANGESTYLE);
	Gura_AssignWxValue(STC_MOD_CHANGEFOLD);
	Gura_AssignWxValue(STC_PERFORMED_USER);
	Gura_AssignWxValue(STC_PERFORMED_UNDO);
	Gura_AssignWxValue(STC_PERFORMED_REDO);
	Gura_AssignWxValue(STC_MULTISTEPUNDOREDO);
	Gura_AssignWxValue(STC_LASTSTEPINUNDOREDO);
	Gura_AssignWxValue(STC_MOD_CHANGEMARKER);
	Gura_AssignWxValue(STC_MOD_BEFOREINSERT);
	Gura_AssignWxValue(STC_MOD_BEFOREDELETE);
	Gura_AssignWxValue(STC_MULTILINEUNDOREDO);
	Gura_AssignWxValue(STC_STARTACTION);
	Gura_AssignWxValue(STC_MOD_CHANGEINDICATOR);
	Gura_AssignWxValue(STC_MOD_CHANGELINESTATE);
	Gura_AssignWxValue(STC_MOD_CHANGEMARGIN);
	Gura_AssignWxValue(STC_MOD_CHANGEANNOTATION);
	Gura_AssignWxValue(STC_MOD_CONTAINER);
	Gura_AssignWxValue(STC_MOD_LEXERSTATE);
	Gura_AssignWxValue(STC_MODEVENTMASKALL);
	Gura_AssignWxValue(STC_UPDATE_CONTENT);
	Gura_AssignWxValue(STC_UPDATE_SELECTION);
	Gura_AssignWxValue(STC_UPDATE_V_SCROLL);
	Gura_AssignWxValue(STC_UPDATE_H_SCROLL);
	Gura_AssignWxValue(STC_KEY_DOWN);
	Gura_AssignWxValue(STC_KEY_UP);
	Gura_AssignWxValue(STC_KEY_LEFT);
	Gura_AssignWxValue(STC_KEY_RIGHT);
	Gura_AssignWxValue(STC_KEY_HOME);
	Gura_AssignWxValue(STC_KEY_END);
	Gura_AssignWxValue(STC_KEY_PRIOR);
	Gura_AssignWxValue(STC_KEY_NEXT);
	Gura_AssignWxValue(STC_KEY_DELETE);
	Gura_AssignWxValue(STC_KEY_INSERT);
	Gura_AssignWxValue(STC_KEY_ESCAPE);
	Gura_AssignWxValue(STC_KEY_BACK);
	Gura_AssignWxValue(STC_KEY_TAB);
	Gura_AssignWxValue(STC_KEY_RETURN);
	Gura_AssignWxValue(STC_KEY_ADD);
	Gura_AssignWxValue(STC_KEY_SUBTRACT);
	Gura_AssignWxValue(STC_KEY_DIVIDE);
	Gura_AssignWxValue(STC_KEY_WIN);
	Gura_AssignWxValue(STC_KEY_RWIN);
	Gura_AssignWxValue(STC_KEY_MENU);
	Gura_AssignWxValue(STC_SCMOD_NORM);
	Gura_AssignWxValue(STC_SCMOD_SHIFT);
	Gura_AssignWxValue(STC_SCMOD_CTRL);
	Gura_AssignWxValue(STC_SCMOD_ALT);
	Gura_AssignWxValue(STC_SCMOD_SUPER);
	Gura_AssignWxValue(STC_SCMOD_META);
	Gura_AssignWxValue(STC_LEX_CONTAINER);
	Gura_AssignWxValue(STC_LEX_NULL);
	Gura_AssignWxValue(STC_LEX_PYTHON);
	Gura_AssignWxValue(STC_LEX_CPP);
	Gura_AssignWxValue(STC_LEX_HTML);
	Gura_AssignWxValue(STC_LEX_XML);
	Gura_AssignWxValue(STC_LEX_PERL);
	Gura_AssignWxValue(STC_LEX_SQL);
	Gura_AssignWxValue(STC_LEX_VB);
	Gura_AssignWxValue(STC_LEX_PROPERTIES);
	Gura_AssignWxValue(STC_LEX_ERRORLIST);
	Gura_AssignWxValue(STC_LEX_MAKEFILE);
	Gura_AssignWxValue(STC_LEX_BATCH);
	Gura_AssignWxValue(STC_LEX_XCODE);
	Gura_AssignWxValue(STC_LEX_LATEX);
	Gura_AssignWxValue(STC_LEX_LUA);
	Gura_AssignWxValue(STC_LEX_DIFF);
	Gura_AssignWxValue(STC_LEX_CONF);
	Gura_AssignWxValue(STC_LEX_PASCAL);
	Gura_AssignWxValue(STC_LEX_AVE);
	Gura_AssignWxValue(STC_LEX_ADA);
	Gura_AssignWxValue(STC_LEX_LISP);
	Gura_AssignWxValue(STC_LEX_RUBY);
	Gura_AssignWxValue(STC_LEX_EIFFEL);
	Gura_AssignWxValue(STC_LEX_EIFFELKW);
	Gura_AssignWxValue(STC_LEX_TCL);
	Gura_AssignWxValue(STC_LEX_NNCRONTAB);
	Gura_AssignWxValue(STC_LEX_BULLANT);
	Gura_AssignWxValue(STC_LEX_VBSCRIPT);
	Gura_AssignWxValue(STC_LEX_BAAN);
	Gura_AssignWxValue(STC_LEX_MATLAB);
	Gura_AssignWxValue(STC_LEX_SCRIPTOL);
	Gura_AssignWxValue(STC_LEX_ASM);
	Gura_AssignWxValue(STC_LEX_CPPNOCASE);
	Gura_AssignWxValue(STC_LEX_FORTRAN);
	Gura_AssignWxValue(STC_LEX_F77);
	Gura_AssignWxValue(STC_LEX_CSS);
	Gura_AssignWxValue(STC_LEX_POV);
	Gura_AssignWxValue(STC_LEX_LOUT);
	Gura_AssignWxValue(STC_LEX_ESCRIPT);
	Gura_AssignWxValue(STC_LEX_PS);
	Gura_AssignWxValue(STC_LEX_NSIS);
	Gura_AssignWxValue(STC_LEX_MMIXAL);
	Gura_AssignWxValue(STC_LEX_CLW);
	Gura_AssignWxValue(STC_LEX_CLWNOCASE);
	Gura_AssignWxValue(STC_LEX_LOT);
	Gura_AssignWxValue(STC_LEX_YAML);
	Gura_AssignWxValue(STC_LEX_TEX);
	Gura_AssignWxValue(STC_LEX_METAPOST);
	Gura_AssignWxValue(STC_LEX_POWERBASIC);
	Gura_AssignWxValue(STC_LEX_FORTH);
	Gura_AssignWxValue(STC_LEX_ERLANG);
	Gura_AssignWxValue(STC_LEX_OCTAVE);
	Gura_AssignWxValue(STC_LEX_MSSQL);
	Gura_AssignWxValue(STC_LEX_VERILOG);
	Gura_AssignWxValue(STC_LEX_KIX);
	Gura_AssignWxValue(STC_LEX_GUI4CLI);
	Gura_AssignWxValue(STC_LEX_SPECMAN);
	Gura_AssignWxValue(STC_LEX_AU3);
	Gura_AssignWxValue(STC_LEX_APDL);
	Gura_AssignWxValue(STC_LEX_BASH);
	Gura_AssignWxValue(STC_LEX_ASN1);
	Gura_AssignWxValue(STC_LEX_VHDL);
	Gura_AssignWxValue(STC_LEX_CAML);
	Gura_AssignWxValue(STC_LEX_BLITZBASIC);
	Gura_AssignWxValue(STC_LEX_PUREBASIC);
	Gura_AssignWxValue(STC_LEX_HASKELL);
	Gura_AssignWxValue(STC_LEX_PHPSCRIPT);
	Gura_AssignWxValue(STC_LEX_TADS3);
	Gura_AssignWxValue(STC_LEX_REBOL);
	Gura_AssignWxValue(STC_LEX_SMALLTALK);
	Gura_AssignWxValue(STC_LEX_FLAGSHIP);
	Gura_AssignWxValue(STC_LEX_CSOUND);
	Gura_AssignWxValue(STC_LEX_FREEBASIC);
	Gura_AssignWxValue(STC_LEX_INNOSETUP);
	Gura_AssignWxValue(STC_LEX_OPAL);
	Gura_AssignWxValue(STC_LEX_SPICE);
	Gura_AssignWxValue(STC_LEX_D);
	Gura_AssignWxValue(STC_LEX_CMAKE);
	Gura_AssignWxValue(STC_LEX_GAP);
	Gura_AssignWxValue(STC_LEX_PLM);
	Gura_AssignWxValue(STC_LEX_PROGRESS);
	Gura_AssignWxValue(STC_LEX_ABAQUS);
	Gura_AssignWxValue(STC_LEX_ASYMPTOTE);
	Gura_AssignWxValue(STC_LEX_R);
	Gura_AssignWxValue(STC_LEX_MAGIK);
	Gura_AssignWxValue(STC_LEX_POWERSHELL);
	Gura_AssignWxValue(STC_LEX_MYSQL);
	Gura_AssignWxValue(STC_LEX_PO);
	Gura_AssignWxValue(STC_LEX_TAL);
	Gura_AssignWxValue(STC_LEX_COBOL);
	Gura_AssignWxValue(STC_LEX_TACL);
	Gura_AssignWxValue(STC_LEX_SORCUS);
	Gura_AssignWxValue(STC_LEX_POWERPRO);
	Gura_AssignWxValue(STC_LEX_NIMROD);
	Gura_AssignWxValue(STC_LEX_SML);
	Gura_AssignWxValue(STC_LEX_MARKDOWN);
	Gura_AssignWxValue(STC_LEX_TXT2TAGS);
	Gura_AssignWxValue(STC_LEX_A68K);
	Gura_AssignWxValue(STC_LEX_MODULA);
	Gura_AssignWxValue(STC_LEX_COFFEESCRIPT);
	Gura_AssignWxValue(STC_LEX_TCMD);
	Gura_AssignWxValue(STC_LEX_AVS);
	Gura_AssignWxValue(STC_LEX_ECL);
	Gura_AssignWxValue(STC_LEX_OSCRIPT);
	Gura_AssignWxValue(STC_LEX_VISUALPROLOG);
	Gura_AssignWxValue(STC_LEX_AUTOMATIC);
	Gura_AssignWxValue(STC_P_DEFAULT);
	Gura_AssignWxValue(STC_P_COMMENTLINE);
	Gura_AssignWxValue(STC_P_NUMBER);
	Gura_AssignWxValue(STC_P_STRING);
	Gura_AssignWxValue(STC_P_CHARACTER);
	Gura_AssignWxValue(STC_P_WORD);
	Gura_AssignWxValue(STC_P_TRIPLE);
	Gura_AssignWxValue(STC_P_TRIPLEDOUBLE);
	Gura_AssignWxValue(STC_P_CLASSNAME);
	Gura_AssignWxValue(STC_P_DEFNAME);
	Gura_AssignWxValue(STC_P_OPERATOR);
	Gura_AssignWxValue(STC_P_IDENTIFIER);
	Gura_AssignWxValue(STC_P_COMMENTBLOCK);
	Gura_AssignWxValue(STC_P_STRINGEOL);
	Gura_AssignWxValue(STC_P_WORD2);
	Gura_AssignWxValue(STC_P_DECORATOR);
	Gura_AssignWxValue(STC_C_DEFAULT);
	Gura_AssignWxValue(STC_C_COMMENT);
	Gura_AssignWxValue(STC_C_COMMENTLINE);
	Gura_AssignWxValue(STC_C_COMMENTDOC);
	Gura_AssignWxValue(STC_C_NUMBER);
	Gura_AssignWxValue(STC_C_WORD);
	Gura_AssignWxValue(STC_C_STRING);
	Gura_AssignWxValue(STC_C_CHARACTER);
	Gura_AssignWxValue(STC_C_UUID);
	Gura_AssignWxValue(STC_C_PREPROCESSOR);
	Gura_AssignWxValue(STC_C_OPERATOR);
	Gura_AssignWxValue(STC_C_IDENTIFIER);
	Gura_AssignWxValue(STC_C_STRINGEOL);
	Gura_AssignWxValue(STC_C_VERBATIM);
	Gura_AssignWxValue(STC_C_REGEX);
	Gura_AssignWxValue(STC_C_COMMENTLINEDOC);
	Gura_AssignWxValue(STC_C_WORD2);
	Gura_AssignWxValue(STC_C_COMMENTDOCKEYWORD);
	Gura_AssignWxValue(STC_C_COMMENTDOCKEYWORDERROR);
	Gura_AssignWxValue(STC_C_GLOBALCLASS);
	Gura_AssignWxValue(STC_C_STRINGRAW);
	Gura_AssignWxValue(STC_C_TRIPLEVERBATIM);
	Gura_AssignWxValue(STC_C_HASHQUOTEDSTRING);
	Gura_AssignWxValue(STC_C_PREPROCESSORCOMMENT);
	Gura_AssignWxValue(STC_D_DEFAULT);
	Gura_AssignWxValue(STC_D_COMMENT);
	Gura_AssignWxValue(STC_D_COMMENTLINE);
	Gura_AssignWxValue(STC_D_COMMENTDOC);
	Gura_AssignWxValue(STC_D_COMMENTNESTED);
	Gura_AssignWxValue(STC_D_NUMBER);
	Gura_AssignWxValue(STC_D_WORD);
	Gura_AssignWxValue(STC_D_WORD2);
	Gura_AssignWxValue(STC_D_WORD3);
	Gura_AssignWxValue(STC_D_TYPEDEF);
	Gura_AssignWxValue(STC_D_STRING);
	Gura_AssignWxValue(STC_D_STRINGEOL);
	Gura_AssignWxValue(STC_D_CHARACTER);
	Gura_AssignWxValue(STC_D_OPERATOR);
	Gura_AssignWxValue(STC_D_IDENTIFIER);
	Gura_AssignWxValue(STC_D_COMMENTLINEDOC);
	Gura_AssignWxValue(STC_D_COMMENTDOCKEYWORD);
	Gura_AssignWxValue(STC_D_COMMENTDOCKEYWORDERROR);
	Gura_AssignWxValue(STC_D_STRINGB);
	Gura_AssignWxValue(STC_D_STRINGR);
	Gura_AssignWxValue(STC_D_WORD5);
	Gura_AssignWxValue(STC_D_WORD6);
	Gura_AssignWxValue(STC_D_WORD7);
	Gura_AssignWxValue(STC_TCL_DEFAULT);
	Gura_AssignWxValue(STC_TCL_COMMENT);
	Gura_AssignWxValue(STC_TCL_COMMENTLINE);
	Gura_AssignWxValue(STC_TCL_NUMBER);
	Gura_AssignWxValue(STC_TCL_WORD_IN_QUOTE);
	Gura_AssignWxValue(STC_TCL_IN_QUOTE);
	Gura_AssignWxValue(STC_TCL_OPERATOR);
	Gura_AssignWxValue(STC_TCL_IDENTIFIER);
	Gura_AssignWxValue(STC_TCL_SUBSTITUTION);
	Gura_AssignWxValue(STC_TCL_SUB_BRACE);
	Gura_AssignWxValue(STC_TCL_MODIFIER);
	Gura_AssignWxValue(STC_TCL_EXPAND);
	Gura_AssignWxValue(STC_TCL_WORD);
	Gura_AssignWxValue(STC_TCL_WORD2);
	Gura_AssignWxValue(STC_TCL_WORD3);
	Gura_AssignWxValue(STC_TCL_WORD4);
	Gura_AssignWxValue(STC_TCL_WORD5);
	Gura_AssignWxValue(STC_TCL_WORD6);
	Gura_AssignWxValue(STC_TCL_WORD7);
	Gura_AssignWxValue(STC_TCL_WORD8);
	Gura_AssignWxValue(STC_TCL_COMMENT_BOX);
	Gura_AssignWxValue(STC_TCL_BLOCK_COMMENT);
	Gura_AssignWxValue(STC_H_DEFAULT);
	Gura_AssignWxValue(STC_H_TAG);
	Gura_AssignWxValue(STC_H_TAGUNKNOWN);
	Gura_AssignWxValue(STC_H_ATTRIBUTE);
	Gura_AssignWxValue(STC_H_ATTRIBUTEUNKNOWN);
	Gura_AssignWxValue(STC_H_NUMBER);
	Gura_AssignWxValue(STC_H_DOUBLESTRING);
	Gura_AssignWxValue(STC_H_SINGLESTRING);
	Gura_AssignWxValue(STC_H_OTHER);
	Gura_AssignWxValue(STC_H_COMMENT);
	Gura_AssignWxValue(STC_H_ENTITY);
	Gura_AssignWxValue(STC_H_TAGEND);
	Gura_AssignWxValue(STC_H_XMLSTART);
	Gura_AssignWxValue(STC_H_XMLEND);
	Gura_AssignWxValue(STC_H_SCRIPT);
	Gura_AssignWxValue(STC_H_ASP);
	Gura_AssignWxValue(STC_H_ASPAT);
	Gura_AssignWxValue(STC_H_CDATA);
	Gura_AssignWxValue(STC_H_QUESTION);
	Gura_AssignWxValue(STC_H_VALUE);
	Gura_AssignWxValue(STC_H_XCCOMMENT);
	Gura_AssignWxValue(STC_H_SGML_DEFAULT);
	Gura_AssignWxValue(STC_H_SGML_COMMAND);
	Gura_AssignWxValue(STC_H_SGML_1ST_PARAM);
	Gura_AssignWxValue(STC_H_SGML_DOUBLESTRING);
	Gura_AssignWxValue(STC_H_SGML_SIMPLESTRING);
	Gura_AssignWxValue(STC_H_SGML_ERROR);
	Gura_AssignWxValue(STC_H_SGML_SPECIAL);
	Gura_AssignWxValue(STC_H_SGML_ENTITY);
	Gura_AssignWxValue(STC_H_SGML_COMMENT);
	Gura_AssignWxValue(STC_H_SGML_1ST_PARAM_COMMENT);
	Gura_AssignWxValue(STC_H_SGML_BLOCK_DEFAULT);
	Gura_AssignWxValue(STC_HJ_START);
	Gura_AssignWxValue(STC_HJ_DEFAULT);
	Gura_AssignWxValue(STC_HJ_COMMENT);
	Gura_AssignWxValue(STC_HJ_COMMENTLINE);
	Gura_AssignWxValue(STC_HJ_COMMENTDOC);
	Gura_AssignWxValue(STC_HJ_NUMBER);
	Gura_AssignWxValue(STC_HJ_WORD);
	Gura_AssignWxValue(STC_HJ_KEYWORD);
	Gura_AssignWxValue(STC_HJ_DOUBLESTRING);
	Gura_AssignWxValue(STC_HJ_SINGLESTRING);
	Gura_AssignWxValue(STC_HJ_SYMBOLS);
	Gura_AssignWxValue(STC_HJ_STRINGEOL);
	Gura_AssignWxValue(STC_HJ_REGEX);
	Gura_AssignWxValue(STC_HJA_START);
	Gura_AssignWxValue(STC_HJA_DEFAULT);
	Gura_AssignWxValue(STC_HJA_COMMENT);
	Gura_AssignWxValue(STC_HJA_COMMENTLINE);
	Gura_AssignWxValue(STC_HJA_COMMENTDOC);
	Gura_AssignWxValue(STC_HJA_NUMBER);
	Gura_AssignWxValue(STC_HJA_WORD);
	Gura_AssignWxValue(STC_HJA_KEYWORD);
	Gura_AssignWxValue(STC_HJA_DOUBLESTRING);
	Gura_AssignWxValue(STC_HJA_SINGLESTRING);
	Gura_AssignWxValue(STC_HJA_SYMBOLS);
	Gura_AssignWxValue(STC_HJA_STRINGEOL);
	Gura_AssignWxValue(STC_HJA_REGEX);
	Gura_AssignWxValue(STC_HB_START);
	Gura_AssignWxValue(STC_HB_DEFAULT);
	Gura_AssignWxValue(STC_HB_COMMENTLINE);
	Gura_AssignWxValue(STC_HB_NUMBER);
	Gura_AssignWxValue(STC_HB_WORD);
	Gura_AssignWxValue(STC_HB_STRING);
	Gura_AssignWxValue(STC_HB_IDENTIFIER);
	Gura_AssignWxValue(STC_HB_STRINGEOL);
	Gura_AssignWxValue(STC_HBA_START);
	Gura_AssignWxValue(STC_HBA_DEFAULT);
	Gura_AssignWxValue(STC_HBA_COMMENTLINE);
	Gura_AssignWxValue(STC_HBA_NUMBER);
	Gura_AssignWxValue(STC_HBA_WORD);
	Gura_AssignWxValue(STC_HBA_STRING);
	Gura_AssignWxValue(STC_HBA_IDENTIFIER);
	Gura_AssignWxValue(STC_HBA_STRINGEOL);
	Gura_AssignWxValue(STC_HP_START);
	Gura_AssignWxValue(STC_HP_DEFAULT);
	Gura_AssignWxValue(STC_HP_COMMENTLINE);
	Gura_AssignWxValue(STC_HP_NUMBER);
	Gura_AssignWxValue(STC_HP_STRING);
	Gura_AssignWxValue(STC_HP_CHARACTER);
	Gura_AssignWxValue(STC_HP_WORD);
	Gura_AssignWxValue(STC_HP_TRIPLE);
	Gura_AssignWxValue(STC_HP_TRIPLEDOUBLE);
	Gura_AssignWxValue(STC_HP_CLASSNAME);
	Gura_AssignWxValue(STC_HP_DEFNAME);
	Gura_AssignWxValue(STC_HP_OPERATOR);
	Gura_AssignWxValue(STC_HP_IDENTIFIER);
	Gura_AssignWxValue(STC_HPHP_COMPLEX_VARIABLE);
	Gura_AssignWxValue(STC_HPA_START);
	Gura_AssignWxValue(STC_HPA_DEFAULT);
	Gura_AssignWxValue(STC_HPA_COMMENTLINE);
	Gura_AssignWxValue(STC_HPA_NUMBER);
	Gura_AssignWxValue(STC_HPA_STRING);
	Gura_AssignWxValue(STC_HPA_CHARACTER);
	Gura_AssignWxValue(STC_HPA_WORD);
	Gura_AssignWxValue(STC_HPA_TRIPLE);
	Gura_AssignWxValue(STC_HPA_TRIPLEDOUBLE);
	Gura_AssignWxValue(STC_HPA_CLASSNAME);
	Gura_AssignWxValue(STC_HPA_DEFNAME);
	Gura_AssignWxValue(STC_HPA_OPERATOR);
	Gura_AssignWxValue(STC_HPA_IDENTIFIER);
	Gura_AssignWxValue(STC_HPHP_DEFAULT);
	Gura_AssignWxValue(STC_HPHP_HSTRING);
	Gura_AssignWxValue(STC_HPHP_SIMPLESTRING);
	Gura_AssignWxValue(STC_HPHP_WORD);
	Gura_AssignWxValue(STC_HPHP_NUMBER);
	Gura_AssignWxValue(STC_HPHP_VARIABLE);
	Gura_AssignWxValue(STC_HPHP_COMMENT);
	Gura_AssignWxValue(STC_HPHP_COMMENTLINE);
	Gura_AssignWxValue(STC_HPHP_HSTRING_VARIABLE);
	Gura_AssignWxValue(STC_HPHP_OPERATOR);
	Gura_AssignWxValue(STC_PL_DEFAULT);
	Gura_AssignWxValue(STC_PL_ERROR);
	Gura_AssignWxValue(STC_PL_COMMENTLINE);
	Gura_AssignWxValue(STC_PL_POD);
	Gura_AssignWxValue(STC_PL_NUMBER);
	Gura_AssignWxValue(STC_PL_WORD);
	Gura_AssignWxValue(STC_PL_STRING);
	Gura_AssignWxValue(STC_PL_CHARACTER);
	Gura_AssignWxValue(STC_PL_PUNCTUATION);
	Gura_AssignWxValue(STC_PL_PREPROCESSOR);
	Gura_AssignWxValue(STC_PL_OPERATOR);
	Gura_AssignWxValue(STC_PL_IDENTIFIER);
	Gura_AssignWxValue(STC_PL_SCALAR);
	Gura_AssignWxValue(STC_PL_ARRAY);
	Gura_AssignWxValue(STC_PL_HASH);
	Gura_AssignWxValue(STC_PL_SYMBOLTABLE);
	Gura_AssignWxValue(STC_PL_VARIABLE_INDEXER);
	Gura_AssignWxValue(STC_PL_REGEX);
	Gura_AssignWxValue(STC_PL_REGSUBST);
	Gura_AssignWxValue(STC_PL_LONGQUOTE);
	Gura_AssignWxValue(STC_PL_BACKTICKS);
	Gura_AssignWxValue(STC_PL_DATASECTION);
	Gura_AssignWxValue(STC_PL_HERE_DELIM);
	Gura_AssignWxValue(STC_PL_HERE_Q);
	Gura_AssignWxValue(STC_PL_HERE_QQ);
	Gura_AssignWxValue(STC_PL_HERE_QX);
	Gura_AssignWxValue(STC_PL_STRING_Q);
	Gura_AssignWxValue(STC_PL_STRING_QQ);
	Gura_AssignWxValue(STC_PL_STRING_QX);
	Gura_AssignWxValue(STC_PL_STRING_QR);
	Gura_AssignWxValue(STC_PL_STRING_QW);
	Gura_AssignWxValue(STC_PL_POD_VERB);
	Gura_AssignWxValue(STC_PL_SUB_PROTOTYPE);
	Gura_AssignWxValue(STC_PL_FORMAT_IDENT);
	Gura_AssignWxValue(STC_PL_FORMAT);
	Gura_AssignWxValue(STC_PL_STRING_VAR);
	Gura_AssignWxValue(STC_PL_XLAT);
	Gura_AssignWxValue(STC_PL_REGEX_VAR);
	Gura_AssignWxValue(STC_PL_REGSUBST_VAR);
	Gura_AssignWxValue(STC_PL_BACKTICKS_VAR);
	Gura_AssignWxValue(STC_PL_HERE_QQ_VAR);
	Gura_AssignWxValue(STC_PL_HERE_QX_VAR);
	Gura_AssignWxValue(STC_PL_STRING_QQ_VAR);
	Gura_AssignWxValue(STC_PL_STRING_QX_VAR);
	Gura_AssignWxValue(STC_PL_STRING_QR_VAR);
	Gura_AssignWxValue(STC_RB_DEFAULT);
	Gura_AssignWxValue(STC_RB_ERROR);
	Gura_AssignWxValue(STC_RB_COMMENTLINE);
	Gura_AssignWxValue(STC_RB_POD);
	Gura_AssignWxValue(STC_RB_NUMBER);
	Gura_AssignWxValue(STC_RB_WORD);
	Gura_AssignWxValue(STC_RB_STRING);
	Gura_AssignWxValue(STC_RB_CHARACTER);
	Gura_AssignWxValue(STC_RB_CLASSNAME);
	Gura_AssignWxValue(STC_RB_DEFNAME);
	Gura_AssignWxValue(STC_RB_OPERATOR);
	Gura_AssignWxValue(STC_RB_IDENTIFIER);
	Gura_AssignWxValue(STC_RB_REGEX);
	Gura_AssignWxValue(STC_RB_GLOBAL);
	Gura_AssignWxValue(STC_RB_SYMBOL);
	Gura_AssignWxValue(STC_RB_MODULE_NAME);
	Gura_AssignWxValue(STC_RB_INSTANCE_VAR);
	Gura_AssignWxValue(STC_RB_CLASS_VAR);
	Gura_AssignWxValue(STC_RB_BACKTICKS);
	Gura_AssignWxValue(STC_RB_DATASECTION);
	Gura_AssignWxValue(STC_RB_HERE_DELIM);
	Gura_AssignWxValue(STC_RB_HERE_Q);
	Gura_AssignWxValue(STC_RB_HERE_QQ);
	Gura_AssignWxValue(STC_RB_HERE_QX);
	Gura_AssignWxValue(STC_RB_STRING_Q);
	Gura_AssignWxValue(STC_RB_STRING_QQ);
	Gura_AssignWxValue(STC_RB_STRING_QX);
	Gura_AssignWxValue(STC_RB_STRING_QR);
	Gura_AssignWxValue(STC_RB_STRING_QW);
	Gura_AssignWxValue(STC_RB_WORD_DEMOTED);
	Gura_AssignWxValue(STC_RB_STDIN);
	Gura_AssignWxValue(STC_RB_STDOUT);
	Gura_AssignWxValue(STC_RB_STDERR);
	Gura_AssignWxValue(STC_RB_UPPER_BOUND);
	Gura_AssignWxValue(STC_B_DEFAULT);
	Gura_AssignWxValue(STC_B_COMMENT);
	Gura_AssignWxValue(STC_B_NUMBER);
	Gura_AssignWxValue(STC_B_KEYWORD);
	Gura_AssignWxValue(STC_B_STRING);
	Gura_AssignWxValue(STC_B_PREPROCESSOR);
	Gura_AssignWxValue(STC_B_OPERATOR);
	Gura_AssignWxValue(STC_B_IDENTIFIER);
	Gura_AssignWxValue(STC_B_DATE);
	Gura_AssignWxValue(STC_B_STRINGEOL);
	Gura_AssignWxValue(STC_B_KEYWORD2);
	Gura_AssignWxValue(STC_B_KEYWORD3);
	Gura_AssignWxValue(STC_B_KEYWORD4);
	Gura_AssignWxValue(STC_B_CONSTANT);
	Gura_AssignWxValue(STC_B_ASM);
	Gura_AssignWxValue(STC_B_LABEL);
	Gura_AssignWxValue(STC_B_ERROR);
	Gura_AssignWxValue(STC_B_HEXNUMBER);
	Gura_AssignWxValue(STC_B_BINNUMBER);
	Gura_AssignWxValue(STC_PROPS_DEFAULT);
	Gura_AssignWxValue(STC_PROPS_COMMENT);
	Gura_AssignWxValue(STC_PROPS_SECTION);
	Gura_AssignWxValue(STC_PROPS_ASSIGNMENT);
	Gura_AssignWxValue(STC_PROPS_DEFVAL);
	Gura_AssignWxValue(STC_PROPS_KEY);
	Gura_AssignWxValue(STC_L_DEFAULT);
	Gura_AssignWxValue(STC_L_COMMAND);
	Gura_AssignWxValue(STC_L_TAG);
	Gura_AssignWxValue(STC_L_MATH);
	Gura_AssignWxValue(STC_L_COMMENT);
	Gura_AssignWxValue(STC_L_TAG2);
	Gura_AssignWxValue(STC_L_MATH2);
	Gura_AssignWxValue(STC_L_COMMENT2);
	Gura_AssignWxValue(STC_L_VERBATIM);
	Gura_AssignWxValue(STC_L_SHORTCMD);
	Gura_AssignWxValue(STC_L_SPECIAL);
	Gura_AssignWxValue(STC_L_CMDOPT);
	Gura_AssignWxValue(STC_L_ERROR);
	Gura_AssignWxValue(STC_LUA_DEFAULT);
	Gura_AssignWxValue(STC_LUA_COMMENT);
	Gura_AssignWxValue(STC_LUA_COMMENTLINE);
	Gura_AssignWxValue(STC_LUA_COMMENTDOC);
	Gura_AssignWxValue(STC_LUA_NUMBER);
	Gura_AssignWxValue(STC_LUA_WORD);
	Gura_AssignWxValue(STC_LUA_STRING);
	Gura_AssignWxValue(STC_LUA_CHARACTER);
	Gura_AssignWxValue(STC_LUA_LITERALSTRING);
	Gura_AssignWxValue(STC_LUA_PREPROCESSOR);
	Gura_AssignWxValue(STC_LUA_OPERATOR);
	Gura_AssignWxValue(STC_LUA_IDENTIFIER);
	Gura_AssignWxValue(STC_LUA_STRINGEOL);
	Gura_AssignWxValue(STC_LUA_WORD2);
	Gura_AssignWxValue(STC_LUA_WORD3);
	Gura_AssignWxValue(STC_LUA_WORD4);
	Gura_AssignWxValue(STC_LUA_WORD5);
	Gura_AssignWxValue(STC_LUA_WORD6);
	Gura_AssignWxValue(STC_LUA_WORD7);
	Gura_AssignWxValue(STC_LUA_WORD8);
	Gura_AssignWxValue(STC_LUA_LABEL);
	Gura_AssignWxValue(STC_ERR_DEFAULT);
	Gura_AssignWxValue(STC_ERR_PYTHON);
	Gura_AssignWxValue(STC_ERR_GCC);
	Gura_AssignWxValue(STC_ERR_MS);
	Gura_AssignWxValue(STC_ERR_CMD);
	Gura_AssignWxValue(STC_ERR_BORLAND);
	Gura_AssignWxValue(STC_ERR_PERL);
	Gura_AssignWxValue(STC_ERR_NET);
	Gura_AssignWxValue(STC_ERR_LUA);
	Gura_AssignWxValue(STC_ERR_CTAG);
	Gura_AssignWxValue(STC_ERR_DIFF_CHANGED);
	Gura_AssignWxValue(STC_ERR_DIFF_ADDITION);
	Gura_AssignWxValue(STC_ERR_DIFF_DELETION);
	Gura_AssignWxValue(STC_ERR_DIFF_MESSAGE);
	Gura_AssignWxValue(STC_ERR_PHP);
	Gura_AssignWxValue(STC_ERR_ELF);
	Gura_AssignWxValue(STC_ERR_IFC);
	Gura_AssignWxValue(STC_ERR_IFORT);
	Gura_AssignWxValue(STC_ERR_ABSF);
	Gura_AssignWxValue(STC_ERR_TIDY);
	Gura_AssignWxValue(STC_ERR_JAVA_STACK);
	Gura_AssignWxValue(STC_ERR_VALUE);
	Gura_AssignWxValue(STC_BAT_DEFAULT);
	Gura_AssignWxValue(STC_BAT_COMMENT);
	Gura_AssignWxValue(STC_BAT_WORD);
	Gura_AssignWxValue(STC_BAT_LABEL);
	Gura_AssignWxValue(STC_BAT_HIDE);
	Gura_AssignWxValue(STC_BAT_COMMAND);
	Gura_AssignWxValue(STC_BAT_IDENTIFIER);
	Gura_AssignWxValue(STC_BAT_OPERATOR);
	Gura_AssignWxValue(STC_TCMD_DEFAULT);
	Gura_AssignWxValue(STC_TCMD_COMMENT);
	Gura_AssignWxValue(STC_TCMD_WORD);
	Gura_AssignWxValue(STC_TCMD_LABEL);
	Gura_AssignWxValue(STC_TCMD_HIDE);
	Gura_AssignWxValue(STC_TCMD_COMMAND);
	Gura_AssignWxValue(STC_TCMD_IDENTIFIER);
	Gura_AssignWxValue(STC_TCMD_OPERATOR);
	Gura_AssignWxValue(STC_TCMD_ENVIRONMENT);
	Gura_AssignWxValue(STC_TCMD_EXPANSION);
	Gura_AssignWxValue(STC_TCMD_CLABEL);
	Gura_AssignWxValue(STC_MAKE_DEFAULT);
	Gura_AssignWxValue(STC_MAKE_COMMENT);
	Gura_AssignWxValue(STC_MAKE_PREPROCESSOR);
	Gura_AssignWxValue(STC_MAKE_IDENTIFIER);
	Gura_AssignWxValue(STC_MAKE_OPERATOR);
	Gura_AssignWxValue(STC_MAKE_TARGET);
	Gura_AssignWxValue(STC_MAKE_IDEOL);
	Gura_AssignWxValue(STC_DIFF_DEFAULT);
	Gura_AssignWxValue(STC_DIFF_COMMENT);
	Gura_AssignWxValue(STC_DIFF_COMMAND);
	Gura_AssignWxValue(STC_DIFF_HEADER);
	Gura_AssignWxValue(STC_DIFF_POSITION);
	Gura_AssignWxValue(STC_DIFF_DELETED);
	Gura_AssignWxValue(STC_DIFF_ADDED);
	Gura_AssignWxValue(STC_DIFF_CHANGED);
	Gura_AssignWxValue(STC_CONF_DEFAULT);
	Gura_AssignWxValue(STC_CONF_COMMENT);
	Gura_AssignWxValue(STC_CONF_NUMBER);
	Gura_AssignWxValue(STC_CONF_IDENTIFIER);
	Gura_AssignWxValue(STC_CONF_EXTENSION);
	Gura_AssignWxValue(STC_CONF_PARAMETER);
	Gura_AssignWxValue(STC_CONF_STRING);
	Gura_AssignWxValue(STC_CONF_OPERATOR);
	Gura_AssignWxValue(STC_CONF_IP);
	Gura_AssignWxValue(STC_CONF_DIRECTIVE);
	Gura_AssignWxValue(STC_AVE_DEFAULT);
	Gura_AssignWxValue(STC_AVE_COMMENT);
	Gura_AssignWxValue(STC_AVE_NUMBER);
	Gura_AssignWxValue(STC_AVE_WORD);
	Gura_AssignWxValue(STC_AVE_STRING);
	Gura_AssignWxValue(STC_AVE_ENUM);
	Gura_AssignWxValue(STC_AVE_STRINGEOL);
	Gura_AssignWxValue(STC_AVE_IDENTIFIER);
	Gura_AssignWxValue(STC_AVE_OPERATOR);
	Gura_AssignWxValue(STC_AVE_WORD1);
	Gura_AssignWxValue(STC_AVE_WORD2);
	Gura_AssignWxValue(STC_AVE_WORD3);
	Gura_AssignWxValue(STC_AVE_WORD4);
	Gura_AssignWxValue(STC_AVE_WORD5);
	Gura_AssignWxValue(STC_AVE_WORD6);
	Gura_AssignWxValue(STC_ADA_DEFAULT);
	Gura_AssignWxValue(STC_ADA_WORD);
	Gura_AssignWxValue(STC_ADA_IDENTIFIER);
	Gura_AssignWxValue(STC_ADA_NUMBER);
	Gura_AssignWxValue(STC_ADA_DELIMITER);
	Gura_AssignWxValue(STC_ADA_CHARACTER);
	Gura_AssignWxValue(STC_ADA_CHARACTEREOL);
	Gura_AssignWxValue(STC_ADA_STRING);
	Gura_AssignWxValue(STC_ADA_STRINGEOL);
	Gura_AssignWxValue(STC_ADA_LABEL);
	Gura_AssignWxValue(STC_ADA_COMMENTLINE);
	Gura_AssignWxValue(STC_ADA_ILLEGAL);
	Gura_AssignWxValue(STC_BAAN_DEFAULT);
	Gura_AssignWxValue(STC_BAAN_COMMENT);
	Gura_AssignWxValue(STC_BAAN_COMMENTDOC);
	Gura_AssignWxValue(STC_BAAN_NUMBER);
	Gura_AssignWxValue(STC_BAAN_WORD);
	Gura_AssignWxValue(STC_BAAN_STRING);
	Gura_AssignWxValue(STC_BAAN_PREPROCESSOR);
	Gura_AssignWxValue(STC_BAAN_OPERATOR);
	Gura_AssignWxValue(STC_BAAN_IDENTIFIER);
	Gura_AssignWxValue(STC_BAAN_STRINGEOL);
	Gura_AssignWxValue(STC_BAAN_WORD2);
	Gura_AssignWxValue(STC_LISP_DEFAULT);
	Gura_AssignWxValue(STC_LISP_COMMENT);
	Gura_AssignWxValue(STC_LISP_NUMBER);
	Gura_AssignWxValue(STC_LISP_KEYWORD);
	Gura_AssignWxValue(STC_LISP_KEYWORD_KW);
	Gura_AssignWxValue(STC_LISP_SYMBOL);
	Gura_AssignWxValue(STC_LISP_STRING);
	Gura_AssignWxValue(STC_LISP_STRINGEOL);
	Gura_AssignWxValue(STC_LISP_IDENTIFIER);
	Gura_AssignWxValue(STC_LISP_OPERATOR);
	Gura_AssignWxValue(STC_LISP_SPECIAL);
	Gura_AssignWxValue(STC_LISP_MULTI_COMMENT);
	Gura_AssignWxValue(STC_EIFFEL_DEFAULT);
	Gura_AssignWxValue(STC_EIFFEL_COMMENTLINE);
	Gura_AssignWxValue(STC_EIFFEL_NUMBER);
	Gura_AssignWxValue(STC_EIFFEL_WORD);
	Gura_AssignWxValue(STC_EIFFEL_STRING);
	Gura_AssignWxValue(STC_EIFFEL_CHARACTER);
	Gura_AssignWxValue(STC_EIFFEL_OPERATOR);
	Gura_AssignWxValue(STC_EIFFEL_IDENTIFIER);
	Gura_AssignWxValue(STC_EIFFEL_STRINGEOL);
	Gura_AssignWxValue(STC_NNCRONTAB_DEFAULT);
	Gura_AssignWxValue(STC_NNCRONTAB_COMMENT);
	Gura_AssignWxValue(STC_NNCRONTAB_TASK);
	Gura_AssignWxValue(STC_NNCRONTAB_SECTION);
	Gura_AssignWxValue(STC_NNCRONTAB_KEYWORD);
	Gura_AssignWxValue(STC_NNCRONTAB_MODIFIER);
	Gura_AssignWxValue(STC_NNCRONTAB_ASTERISK);
	Gura_AssignWxValue(STC_NNCRONTAB_NUMBER);
	Gura_AssignWxValue(STC_NNCRONTAB_STRING);
	Gura_AssignWxValue(STC_NNCRONTAB_ENVIRONMENT);
	Gura_AssignWxValue(STC_NNCRONTAB_IDENTIFIER);
	Gura_AssignWxValue(STC_FORTH_DEFAULT);
	Gura_AssignWxValue(STC_FORTH_COMMENT);
	Gura_AssignWxValue(STC_FORTH_COMMENT_ML);
	Gura_AssignWxValue(STC_FORTH_IDENTIFIER);
	Gura_AssignWxValue(STC_FORTH_CONTROL);
	Gura_AssignWxValue(STC_FORTH_KEYWORD);
	Gura_AssignWxValue(STC_FORTH_DEFWORD);
	Gura_AssignWxValue(STC_FORTH_PREWORD1);
	Gura_AssignWxValue(STC_FORTH_PREWORD2);
	Gura_AssignWxValue(STC_FORTH_NUMBER);
	Gura_AssignWxValue(STC_FORTH_STRING);
	Gura_AssignWxValue(STC_FORTH_LOCALE);
	Gura_AssignWxValue(STC_MATLAB_DEFAULT);
	Gura_AssignWxValue(STC_MATLAB_COMMENT);
	Gura_AssignWxValue(STC_MATLAB_COMMAND);
	Gura_AssignWxValue(STC_MATLAB_NUMBER);
	Gura_AssignWxValue(STC_MATLAB_KEYWORD);
	Gura_AssignWxValue(STC_MATLAB_STRING);
	Gura_AssignWxValue(STC_MATLAB_OPERATOR);
	Gura_AssignWxValue(STC_MATLAB_IDENTIFIER);
	Gura_AssignWxValue(STC_MATLAB_DOUBLEQUOTESTRING);
	Gura_AssignWxValue(STC_SCRIPTOL_DEFAULT);
	Gura_AssignWxValue(STC_SCRIPTOL_WHITE);
	Gura_AssignWxValue(STC_SCRIPTOL_COMMENTLINE);
	Gura_AssignWxValue(STC_SCRIPTOL_PERSISTENT);
	Gura_AssignWxValue(STC_SCRIPTOL_CSTYLE);
	Gura_AssignWxValue(STC_SCRIPTOL_COMMENTBLOCK);
	Gura_AssignWxValue(STC_SCRIPTOL_NUMBER);
	Gura_AssignWxValue(STC_SCRIPTOL_STRING);
	Gura_AssignWxValue(STC_SCRIPTOL_CHARACTER);
	Gura_AssignWxValue(STC_SCRIPTOL_STRINGEOL);
	Gura_AssignWxValue(STC_SCRIPTOL_KEYWORD);
	Gura_AssignWxValue(STC_SCRIPTOL_OPERATOR);
	Gura_AssignWxValue(STC_SCRIPTOL_IDENTIFIER);
	Gura_AssignWxValue(STC_SCRIPTOL_TRIPLE);
	Gura_AssignWxValue(STC_SCRIPTOL_CLASSNAME);
	Gura_AssignWxValue(STC_SCRIPTOL_PREPROCESSOR);
	Gura_AssignWxValue(STC_ASM_DEFAULT);
	Gura_AssignWxValue(STC_ASM_COMMENT);
	Gura_AssignWxValue(STC_ASM_NUMBER);
	Gura_AssignWxValue(STC_ASM_STRING);
	Gura_AssignWxValue(STC_ASM_OPERATOR);
	Gura_AssignWxValue(STC_ASM_IDENTIFIER);
	Gura_AssignWxValue(STC_ASM_CPUINSTRUCTION);
	Gura_AssignWxValue(STC_ASM_MATHINSTRUCTION);
	Gura_AssignWxValue(STC_ASM_REGISTER);
	Gura_AssignWxValue(STC_ASM_DIRECTIVE);
	Gura_AssignWxValue(STC_ASM_DIRECTIVEOPERAND);
	Gura_AssignWxValue(STC_ASM_COMMENTBLOCK);
	Gura_AssignWxValue(STC_ASM_CHARACTER);
	Gura_AssignWxValue(STC_ASM_STRINGEOL);
	Gura_AssignWxValue(STC_ASM_EXTINSTRUCTION);
	Gura_AssignWxValue(STC_ASM_COMMENTDIRECTIVE);
	Gura_AssignWxValue(STC_F_DEFAULT);
	Gura_AssignWxValue(STC_F_COMMENT);
	Gura_AssignWxValue(STC_F_NUMBER);
	Gura_AssignWxValue(STC_F_STRING1);
	Gura_AssignWxValue(STC_F_STRING2);
	Gura_AssignWxValue(STC_F_STRINGEOL);
	Gura_AssignWxValue(STC_F_OPERATOR);
	Gura_AssignWxValue(STC_F_IDENTIFIER);
	Gura_AssignWxValue(STC_F_WORD);
	Gura_AssignWxValue(STC_F_WORD2);
	Gura_AssignWxValue(STC_F_WORD3);
	Gura_AssignWxValue(STC_F_PREPROCESSOR);
	Gura_AssignWxValue(STC_F_OPERATOR2);
	Gura_AssignWxValue(STC_F_LABEL);
	Gura_AssignWxValue(STC_F_CONTINUATION);
	Gura_AssignWxValue(STC_CSS_DEFAULT);
	Gura_AssignWxValue(STC_CSS_TAG);
	Gura_AssignWxValue(STC_CSS_CLASS);
	Gura_AssignWxValue(STC_CSS_PSEUDOCLASS);
	Gura_AssignWxValue(STC_CSS_UNKNOWN_PSEUDOCLASS);
	Gura_AssignWxValue(STC_CSS_OPERATOR);
	Gura_AssignWxValue(STC_CSS_IDENTIFIER);
	Gura_AssignWxValue(STC_CSS_UNKNOWN_IDENTIFIER);
	Gura_AssignWxValue(STC_CSS_VALUE);
	Gura_AssignWxValue(STC_CSS_COMMENT);
	Gura_AssignWxValue(STC_CSS_ID);
	Gura_AssignWxValue(STC_CSS_IMPORTANT);
	Gura_AssignWxValue(STC_CSS_DIRECTIVE);
	Gura_AssignWxValue(STC_CSS_DOUBLESTRING);
	Gura_AssignWxValue(STC_CSS_SINGLESTRING);
	Gura_AssignWxValue(STC_CSS_IDENTIFIER2);
	Gura_AssignWxValue(STC_CSS_ATTRIBUTE);
	Gura_AssignWxValue(STC_CSS_IDENTIFIER3);
	Gura_AssignWxValue(STC_CSS_PSEUDOELEMENT);
	Gura_AssignWxValue(STC_CSS_EXTENDED_IDENTIFIER);
	Gura_AssignWxValue(STC_CSS_EXTENDED_PSEUDOCLASS);
	Gura_AssignWxValue(STC_CSS_EXTENDED_PSEUDOELEMENT);
	Gura_AssignWxValue(STC_CSS_MEDIA);
	Gura_AssignWxValue(STC_CSS_VARIABLE);
	Gura_AssignWxValue(STC_POV_DEFAULT);
	Gura_AssignWxValue(STC_POV_COMMENT);
	Gura_AssignWxValue(STC_POV_COMMENTLINE);
	Gura_AssignWxValue(STC_POV_NUMBER);
	Gura_AssignWxValue(STC_POV_OPERATOR);
	Gura_AssignWxValue(STC_POV_IDENTIFIER);
	Gura_AssignWxValue(STC_POV_STRING);
	Gura_AssignWxValue(STC_POV_STRINGEOL);
	Gura_AssignWxValue(STC_POV_DIRECTIVE);
	Gura_AssignWxValue(STC_POV_BADDIRECTIVE);
	Gura_AssignWxValue(STC_POV_WORD2);
	Gura_AssignWxValue(STC_POV_WORD3);
	Gura_AssignWxValue(STC_POV_WORD4);
	Gura_AssignWxValue(STC_POV_WORD5);
	Gura_AssignWxValue(STC_POV_WORD6);
	Gura_AssignWxValue(STC_POV_WORD7);
	Gura_AssignWxValue(STC_POV_WORD8);
	Gura_AssignWxValue(STC_LOUT_DEFAULT);
	Gura_AssignWxValue(STC_LOUT_COMMENT);
	Gura_AssignWxValue(STC_LOUT_NUMBER);
	Gura_AssignWxValue(STC_LOUT_WORD);
	Gura_AssignWxValue(STC_LOUT_WORD2);
	Gura_AssignWxValue(STC_LOUT_WORD3);
	Gura_AssignWxValue(STC_LOUT_WORD4);
	Gura_AssignWxValue(STC_LOUT_STRING);
	Gura_AssignWxValue(STC_LOUT_OPERATOR);
	Gura_AssignWxValue(STC_LOUT_IDENTIFIER);
	Gura_AssignWxValue(STC_LOUT_STRINGEOL);
	Gura_AssignWxValue(STC_ESCRIPT_DEFAULT);
	Gura_AssignWxValue(STC_ESCRIPT_COMMENT);
	Gura_AssignWxValue(STC_ESCRIPT_COMMENTLINE);
	Gura_AssignWxValue(STC_ESCRIPT_COMMENTDOC);
	Gura_AssignWxValue(STC_ESCRIPT_NUMBER);
	Gura_AssignWxValue(STC_ESCRIPT_WORD);
	Gura_AssignWxValue(STC_ESCRIPT_STRING);
	Gura_AssignWxValue(STC_ESCRIPT_OPERATOR);
	Gura_AssignWxValue(STC_ESCRIPT_IDENTIFIER);
	Gura_AssignWxValue(STC_ESCRIPT_BRACE);
	Gura_AssignWxValue(STC_ESCRIPT_WORD2);
	Gura_AssignWxValue(STC_ESCRIPT_WORD3);
	Gura_AssignWxValue(STC_PS_DEFAULT);
	Gura_AssignWxValue(STC_PS_COMMENT);
	Gura_AssignWxValue(STC_PS_DSC_COMMENT);
	Gura_AssignWxValue(STC_PS_DSC_VALUE);
	Gura_AssignWxValue(STC_PS_NUMBER);
	Gura_AssignWxValue(STC_PS_NAME);
	Gura_AssignWxValue(STC_PS_KEYWORD);
	Gura_AssignWxValue(STC_PS_LITERAL);
	Gura_AssignWxValue(STC_PS_IMMEVAL);
	Gura_AssignWxValue(STC_PS_PAREN_ARRAY);
	Gura_AssignWxValue(STC_PS_PAREN_DICT);
	Gura_AssignWxValue(STC_PS_PAREN_PROC);
	Gura_AssignWxValue(STC_PS_TEXT);
	Gura_AssignWxValue(STC_PS_HEXSTRING);
	Gura_AssignWxValue(STC_PS_BASE85STRING);
	Gura_AssignWxValue(STC_PS_BADSTRINGCHAR);
	Gura_AssignWxValue(STC_NSIS_DEFAULT);
	Gura_AssignWxValue(STC_NSIS_COMMENT);
	Gura_AssignWxValue(STC_NSIS_STRINGDQ);
	Gura_AssignWxValue(STC_NSIS_STRINGLQ);
	Gura_AssignWxValue(STC_NSIS_STRINGRQ);
	Gura_AssignWxValue(STC_NSIS_FUNCTION);
	Gura_AssignWxValue(STC_NSIS_VARIABLE);
	Gura_AssignWxValue(STC_NSIS_LABEL);
	Gura_AssignWxValue(STC_NSIS_USERDEFINED);
	Gura_AssignWxValue(STC_NSIS_SECTIONDEF);
	Gura_AssignWxValue(STC_NSIS_SUBSECTIONDEF);
	Gura_AssignWxValue(STC_NSIS_IFDEFINEDEF);
	Gura_AssignWxValue(STC_NSIS_MACRODEF);
	Gura_AssignWxValue(STC_NSIS_STRINGVAR);
	Gura_AssignWxValue(STC_NSIS_NUMBER);
	Gura_AssignWxValue(STC_NSIS_SECTIONGROUP);
	Gura_AssignWxValue(STC_NSIS_PAGEEX);
	Gura_AssignWxValue(STC_NSIS_FUNCTIONDEF);
	Gura_AssignWxValue(STC_NSIS_COMMENTBOX);
	Gura_AssignWxValue(STC_MMIXAL_LEADWS);
	Gura_AssignWxValue(STC_MMIXAL_COMMENT);
	Gura_AssignWxValue(STC_MMIXAL_LABEL);
	Gura_AssignWxValue(STC_MMIXAL_OPCODE);
	Gura_AssignWxValue(STC_MMIXAL_OPCODE_PRE);
	Gura_AssignWxValue(STC_MMIXAL_OPCODE_VALID);
	Gura_AssignWxValue(STC_MMIXAL_OPCODE_UNKNOWN);
	Gura_AssignWxValue(STC_MMIXAL_OPCODE_POST);
	Gura_AssignWxValue(STC_MMIXAL_OPERANDS);
	Gura_AssignWxValue(STC_MMIXAL_NUMBER);
	Gura_AssignWxValue(STC_MMIXAL_REF);
	Gura_AssignWxValue(STC_MMIXAL_CHAR);
	Gura_AssignWxValue(STC_MMIXAL_STRING);
	Gura_AssignWxValue(STC_MMIXAL_REGISTER);
	Gura_AssignWxValue(STC_MMIXAL_HEX);
	Gura_AssignWxValue(STC_MMIXAL_OPERATOR);
	Gura_AssignWxValue(STC_MMIXAL_SYMBOL);
	Gura_AssignWxValue(STC_MMIXAL_INCLUDE);
	Gura_AssignWxValue(STC_CLW_DEFAULT);
	Gura_AssignWxValue(STC_CLW_LABEL);
	Gura_AssignWxValue(STC_CLW_COMMENT);
	Gura_AssignWxValue(STC_CLW_STRING);
	Gura_AssignWxValue(STC_CLW_USER_IDENTIFIER);
	Gura_AssignWxValue(STC_CLW_INTEGER_CONSTANT);
	Gura_AssignWxValue(STC_CLW_REAL_CONSTANT);
	Gura_AssignWxValue(STC_CLW_PICTURE_STRING);
	Gura_AssignWxValue(STC_CLW_KEYWORD);
	Gura_AssignWxValue(STC_CLW_COMPILER_DIRECTIVE);
	Gura_AssignWxValue(STC_CLW_RUNTIME_EXPRESSIONS);
	Gura_AssignWxValue(STC_CLW_BUILTIN_PROCEDURES_FUNCTION);
	Gura_AssignWxValue(STC_CLW_STRUCTURE_DATA_TYPE);
	Gura_AssignWxValue(STC_CLW_ATTRIBUTE);
	Gura_AssignWxValue(STC_CLW_STANDARD_EQUATE);
	Gura_AssignWxValue(STC_CLW_ERROR);
	Gura_AssignWxValue(STC_CLW_DEPRECATED);
	Gura_AssignWxValue(STC_LOT_DEFAULT);
	Gura_AssignWxValue(STC_LOT_HEADER);
	Gura_AssignWxValue(STC_LOT_BREAK);
	Gura_AssignWxValue(STC_LOT_SET);
	Gura_AssignWxValue(STC_LOT_PASS);
	Gura_AssignWxValue(STC_LOT_FAIL);
	Gura_AssignWxValue(STC_LOT_ABORT);
	Gura_AssignWxValue(STC_YAML_DEFAULT);
	Gura_AssignWxValue(STC_YAML_COMMENT);
	Gura_AssignWxValue(STC_YAML_IDENTIFIER);
	Gura_AssignWxValue(STC_YAML_KEYWORD);
	Gura_AssignWxValue(STC_YAML_NUMBER);
	Gura_AssignWxValue(STC_YAML_REFERENCE);
	Gura_AssignWxValue(STC_YAML_DOCUMENT);
	Gura_AssignWxValue(STC_YAML_TEXT);
	Gura_AssignWxValue(STC_YAML_ERROR);
	Gura_AssignWxValue(STC_YAML_OPERATOR);
	Gura_AssignWxValue(STC_TEX_DEFAULT);
	Gura_AssignWxValue(STC_TEX_SPECIAL);
	Gura_AssignWxValue(STC_TEX_GROUP);
	Gura_AssignWxValue(STC_TEX_SYMBOL);
	Gura_AssignWxValue(STC_TEX_COMMAND);
	Gura_AssignWxValue(STC_TEX_TEXT);
	Gura_AssignWxValue(STC_METAPOST_DEFAULT);
	Gura_AssignWxValue(STC_METAPOST_SPECIAL);
	Gura_AssignWxValue(STC_METAPOST_GROUP);
	Gura_AssignWxValue(STC_METAPOST_SYMBOL);
	Gura_AssignWxValue(STC_METAPOST_COMMAND);
	Gura_AssignWxValue(STC_METAPOST_TEXT);
	Gura_AssignWxValue(STC_METAPOST_EXTRA);
	Gura_AssignWxValue(STC_ERLANG_DEFAULT);
	Gura_AssignWxValue(STC_ERLANG_COMMENT);
	Gura_AssignWxValue(STC_ERLANG_VARIABLE);
	Gura_AssignWxValue(STC_ERLANG_NUMBER);
	Gura_AssignWxValue(STC_ERLANG_KEYWORD);
	Gura_AssignWxValue(STC_ERLANG_STRING);
	Gura_AssignWxValue(STC_ERLANG_OPERATOR);
	Gura_AssignWxValue(STC_ERLANG_ATOM);
	Gura_AssignWxValue(STC_ERLANG_FUNCTION_NAME);
	Gura_AssignWxValue(STC_ERLANG_CHARACTER);
	Gura_AssignWxValue(STC_ERLANG_MACRO);
	Gura_AssignWxValue(STC_ERLANG_RECORD);
	Gura_AssignWxValue(STC_ERLANG_PREPROC);
	Gura_AssignWxValue(STC_ERLANG_NODE_NAME);
	Gura_AssignWxValue(STC_ERLANG_COMMENT_FUNCTION);
	Gura_AssignWxValue(STC_ERLANG_COMMENT_MODULE);
	Gura_AssignWxValue(STC_ERLANG_COMMENT_DOC);
	Gura_AssignWxValue(STC_ERLANG_COMMENT_DOC_MACRO);
	Gura_AssignWxValue(STC_ERLANG_ATOM_QUOTED);
	Gura_AssignWxValue(STC_ERLANG_MACRO_QUOTED);
	Gura_AssignWxValue(STC_ERLANG_RECORD_QUOTED);
	Gura_AssignWxValue(STC_ERLANG_NODE_NAME_QUOTED);
	Gura_AssignWxValue(STC_ERLANG_BIFS);
	Gura_AssignWxValue(STC_ERLANG_MODULES);
	Gura_AssignWxValue(STC_ERLANG_MODULES_ATT);
	Gura_AssignWxValue(STC_ERLANG_UNKNOWN);
	Gura_AssignWxValue(STC_MSSQL_DEFAULT);
	Gura_AssignWxValue(STC_MSSQL_COMMENT);
	Gura_AssignWxValue(STC_MSSQL_LINE_COMMENT);
	Gura_AssignWxValue(STC_MSSQL_NUMBER);
	Gura_AssignWxValue(STC_MSSQL_STRING);
	Gura_AssignWxValue(STC_MSSQL_OPERATOR);
	Gura_AssignWxValue(STC_MSSQL_IDENTIFIER);
	Gura_AssignWxValue(STC_MSSQL_VARIABLE);
	Gura_AssignWxValue(STC_MSSQL_COLUMN_NAME);
	Gura_AssignWxValue(STC_MSSQL_STATEMENT);
	Gura_AssignWxValue(STC_MSSQL_DATATYPE);
	Gura_AssignWxValue(STC_MSSQL_SYSTABLE);
	Gura_AssignWxValue(STC_MSSQL_GLOBAL_VARIABLE);
	Gura_AssignWxValue(STC_MSSQL_FUNCTION);
	Gura_AssignWxValue(STC_MSSQL_STORED_PROCEDURE);
	Gura_AssignWxValue(STC_MSSQL_DEFAULT_PREF_DATATYPE);
	Gura_AssignWxValue(STC_MSSQL_COLUMN_NAME_2);
	Gura_AssignWxValue(STC_V_DEFAULT);
	Gura_AssignWxValue(STC_V_COMMENT);
	Gura_AssignWxValue(STC_V_COMMENTLINE);
	Gura_AssignWxValue(STC_V_COMMENTLINEBANG);
	Gura_AssignWxValue(STC_V_NUMBER);
	Gura_AssignWxValue(STC_V_WORD);
	Gura_AssignWxValue(STC_V_STRING);
	Gura_AssignWxValue(STC_V_WORD2);
	Gura_AssignWxValue(STC_V_WORD3);
	Gura_AssignWxValue(STC_V_PREPROCESSOR);
	Gura_AssignWxValue(STC_V_OPERATOR);
	Gura_AssignWxValue(STC_V_IDENTIFIER);
	Gura_AssignWxValue(STC_V_STRINGEOL);
	Gura_AssignWxValue(STC_V_USER);
	Gura_AssignWxValue(STC_KIX_DEFAULT);
	Gura_AssignWxValue(STC_KIX_COMMENT);
	Gura_AssignWxValue(STC_KIX_STRING1);
	Gura_AssignWxValue(STC_KIX_STRING2);
	Gura_AssignWxValue(STC_KIX_NUMBER);
	Gura_AssignWxValue(STC_KIX_VAR);
	Gura_AssignWxValue(STC_KIX_MACRO);
	Gura_AssignWxValue(STC_KIX_KEYWORD);
	Gura_AssignWxValue(STC_KIX_FUNCTIONS);
	Gura_AssignWxValue(STC_KIX_OPERATOR);
	Gura_AssignWxValue(STC_KIX_IDENTIFIER);
	Gura_AssignWxValue(STC_GC_DEFAULT);
	Gura_AssignWxValue(STC_GC_COMMENTLINE);
	Gura_AssignWxValue(STC_GC_COMMENTBLOCK);
	Gura_AssignWxValue(STC_GC_GLOBAL);
	Gura_AssignWxValue(STC_GC_EVENT);
	Gura_AssignWxValue(STC_GC_ATTRIBUTE);
	Gura_AssignWxValue(STC_GC_CONTROL);
	Gura_AssignWxValue(STC_GC_COMMAND);
	Gura_AssignWxValue(STC_GC_STRING);
	Gura_AssignWxValue(STC_GC_OPERATOR);
	Gura_AssignWxValue(STC_SN_DEFAULT);
	Gura_AssignWxValue(STC_SN_CODE);
	Gura_AssignWxValue(STC_SN_COMMENTLINE);
	Gura_AssignWxValue(STC_SN_COMMENTLINEBANG);
	Gura_AssignWxValue(STC_SN_NUMBER);
	Gura_AssignWxValue(STC_SN_WORD);
	Gura_AssignWxValue(STC_SN_STRING);
	Gura_AssignWxValue(STC_SN_WORD2);
	Gura_AssignWxValue(STC_SN_WORD3);
	Gura_AssignWxValue(STC_SN_PREPROCESSOR);
	Gura_AssignWxValue(STC_SN_OPERATOR);
	Gura_AssignWxValue(STC_SN_IDENTIFIER);
	Gura_AssignWxValue(STC_SN_STRINGEOL);
	Gura_AssignWxValue(STC_SN_REGEXTAG);
	Gura_AssignWxValue(STC_SN_SIGNAL);
	Gura_AssignWxValue(STC_SN_USER);
	Gura_AssignWxValue(STC_AU3_DEFAULT);
	Gura_AssignWxValue(STC_AU3_COMMENT);
	Gura_AssignWxValue(STC_AU3_COMMENTBLOCK);
	Gura_AssignWxValue(STC_AU3_NUMBER);
	Gura_AssignWxValue(STC_AU3_FUNCTION);
	Gura_AssignWxValue(STC_AU3_KEYWORD);
	Gura_AssignWxValue(STC_AU3_MACRO);
	Gura_AssignWxValue(STC_AU3_STRING);
	Gura_AssignWxValue(STC_AU3_OPERATOR);
	Gura_AssignWxValue(STC_AU3_VARIABLE);
	Gura_AssignWxValue(STC_AU3_SENT);
	Gura_AssignWxValue(STC_AU3_PREPROCESSOR);
	Gura_AssignWxValue(STC_AU3_SPECIAL);
	Gura_AssignWxValue(STC_AU3_EXPAND);
	Gura_AssignWxValue(STC_AU3_COMOBJ);
	Gura_AssignWxValue(STC_AU3_UDF);
	Gura_AssignWxValue(STC_APDL_DEFAULT);
	Gura_AssignWxValue(STC_APDL_COMMENT);
	Gura_AssignWxValue(STC_APDL_COMMENTBLOCK);
	Gura_AssignWxValue(STC_APDL_NUMBER);
	Gura_AssignWxValue(STC_APDL_STRING);
	Gura_AssignWxValue(STC_APDL_OPERATOR);
	Gura_AssignWxValue(STC_APDL_WORD);
	Gura_AssignWxValue(STC_APDL_PROCESSOR);
	Gura_AssignWxValue(STC_APDL_COMMAND);
	Gura_AssignWxValue(STC_APDL_SLASHCOMMAND);
	Gura_AssignWxValue(STC_APDL_STARCOMMAND);
	Gura_AssignWxValue(STC_APDL_ARGUMENT);
	Gura_AssignWxValue(STC_APDL_FUNCTION);
	Gura_AssignWxValue(STC_SH_DEFAULT);
	Gura_AssignWxValue(STC_SH_ERROR);
	Gura_AssignWxValue(STC_SH_COMMENTLINE);
	Gura_AssignWxValue(STC_SH_NUMBER);
	Gura_AssignWxValue(STC_SH_WORD);
	Gura_AssignWxValue(STC_SH_STRING);
	Gura_AssignWxValue(STC_SH_CHARACTER);
	Gura_AssignWxValue(STC_SH_OPERATOR);
	Gura_AssignWxValue(STC_SH_IDENTIFIER);
	Gura_AssignWxValue(STC_SH_SCALAR);
	Gura_AssignWxValue(STC_SH_PARAM);
	Gura_AssignWxValue(STC_SH_BACKTICKS);
	Gura_AssignWxValue(STC_SH_HERE_DELIM);
	Gura_AssignWxValue(STC_SH_HERE_Q);
	Gura_AssignWxValue(STC_ASN1_DEFAULT);
	Gura_AssignWxValue(STC_ASN1_COMMENT);
	Gura_AssignWxValue(STC_ASN1_IDENTIFIER);
	Gura_AssignWxValue(STC_ASN1_STRING);
	Gura_AssignWxValue(STC_ASN1_OID);
	Gura_AssignWxValue(STC_ASN1_SCALAR);
	Gura_AssignWxValue(STC_ASN1_KEYWORD);
	Gura_AssignWxValue(STC_ASN1_ATTRIBUTE);
	Gura_AssignWxValue(STC_ASN1_DESCRIPTOR);
	Gura_AssignWxValue(STC_ASN1_TYPE);
	Gura_AssignWxValue(STC_ASN1_OPERATOR);
	Gura_AssignWxValue(STC_VHDL_DEFAULT);
	Gura_AssignWxValue(STC_VHDL_COMMENT);
	Gura_AssignWxValue(STC_VHDL_COMMENTLINEBANG);
	Gura_AssignWxValue(STC_VHDL_NUMBER);
	Gura_AssignWxValue(STC_VHDL_STRING);
	Gura_AssignWxValue(STC_VHDL_OPERATOR);
	Gura_AssignWxValue(STC_VHDL_IDENTIFIER);
	Gura_AssignWxValue(STC_VHDL_STRINGEOL);
	Gura_AssignWxValue(STC_VHDL_KEYWORD);
	Gura_AssignWxValue(STC_VHDL_STDOPERATOR);
	Gura_AssignWxValue(STC_VHDL_ATTRIBUTE);
	Gura_AssignWxValue(STC_VHDL_STDFUNCTION);
	Gura_AssignWxValue(STC_VHDL_STDPACKAGE);
	Gura_AssignWxValue(STC_VHDL_STDTYPE);
	Gura_AssignWxValue(STC_VHDL_USERWORD);
	Gura_AssignWxValue(STC_CAML_DEFAULT);
	Gura_AssignWxValue(STC_CAML_IDENTIFIER);
	Gura_AssignWxValue(STC_CAML_TAGNAME);
	Gura_AssignWxValue(STC_CAML_KEYWORD);
	Gura_AssignWxValue(STC_CAML_KEYWORD2);
	Gura_AssignWxValue(STC_CAML_KEYWORD3);
	Gura_AssignWxValue(STC_CAML_LINENUM);
	Gura_AssignWxValue(STC_CAML_OPERATOR);
	Gura_AssignWxValue(STC_CAML_NUMBER);
	Gura_AssignWxValue(STC_CAML_CHAR);
	Gura_AssignWxValue(STC_CAML_WHITE);
	Gura_AssignWxValue(STC_CAML_STRING);
	Gura_AssignWxValue(STC_CAML_COMMENT);
	Gura_AssignWxValue(STC_CAML_COMMENT1);
	Gura_AssignWxValue(STC_CAML_COMMENT2);
	Gura_AssignWxValue(STC_CAML_COMMENT3);
	Gura_AssignWxValue(STC_HA_DEFAULT);
	Gura_AssignWxValue(STC_HA_IDENTIFIER);
	Gura_AssignWxValue(STC_HA_KEYWORD);
	Gura_AssignWxValue(STC_HA_NUMBER);
	Gura_AssignWxValue(STC_HA_STRING);
	Gura_AssignWxValue(STC_HA_CHARACTER);
	Gura_AssignWxValue(STC_HA_CLASS);
	Gura_AssignWxValue(STC_HA_MODULE);
	Gura_AssignWxValue(STC_HA_CAPITAL);
	Gura_AssignWxValue(STC_HA_DATA);
	Gura_AssignWxValue(STC_HA_IMPORT);
	Gura_AssignWxValue(STC_HA_OPERATOR);
	Gura_AssignWxValue(STC_HA_INSTANCE);
	Gura_AssignWxValue(STC_HA_COMMENTLINE);
	Gura_AssignWxValue(STC_HA_COMMENTBLOCK);
	Gura_AssignWxValue(STC_HA_COMMENTBLOCK2);
	Gura_AssignWxValue(STC_HA_COMMENTBLOCK3);
	Gura_AssignWxValue(STC_T3_DEFAULT);
	Gura_AssignWxValue(STC_T3_X_DEFAULT);
	Gura_AssignWxValue(STC_T3_PREPROCESSOR);
	Gura_AssignWxValue(STC_T3_BLOCK_COMMENT);
	Gura_AssignWxValue(STC_T3_LINE_COMMENT);
	Gura_AssignWxValue(STC_T3_OPERATOR);
	Gura_AssignWxValue(STC_T3_KEYWORD);
	Gura_AssignWxValue(STC_T3_NUMBER);
	Gura_AssignWxValue(STC_T3_IDENTIFIER);
	Gura_AssignWxValue(STC_T3_S_STRING);
	Gura_AssignWxValue(STC_T3_D_STRING);
	Gura_AssignWxValue(STC_T3_X_STRING);
	Gura_AssignWxValue(STC_T3_LIB_DIRECTIVE);
	Gura_AssignWxValue(STC_T3_MSG_PARAM);
	Gura_AssignWxValue(STC_T3_HTML_TAG);
	Gura_AssignWxValue(STC_T3_HTML_DEFAULT);
	Gura_AssignWxValue(STC_T3_HTML_STRING);
	Gura_AssignWxValue(STC_T3_USER1);
	Gura_AssignWxValue(STC_T3_USER2);
	Gura_AssignWxValue(STC_T3_USER3);
	Gura_AssignWxValue(STC_T3_BRACE);
	Gura_AssignWxValue(STC_REBOL_DEFAULT);
	Gura_AssignWxValue(STC_REBOL_COMMENTLINE);
	Gura_AssignWxValue(STC_REBOL_COMMENTBLOCK);
	Gura_AssignWxValue(STC_REBOL_PREFACE);
	Gura_AssignWxValue(STC_REBOL_OPERATOR);
	Gura_AssignWxValue(STC_REBOL_CHARACTER);
	Gura_AssignWxValue(STC_REBOL_QUOTEDSTRING);
	Gura_AssignWxValue(STC_REBOL_BRACEDSTRING);
	Gura_AssignWxValue(STC_REBOL_NUMBER);
	Gura_AssignWxValue(STC_REBOL_PAIR);
	Gura_AssignWxValue(STC_REBOL_TUPLE);
	Gura_AssignWxValue(STC_REBOL_BINARY);
	Gura_AssignWxValue(STC_REBOL_MONEY);
	Gura_AssignWxValue(STC_REBOL_ISSUE);
	Gura_AssignWxValue(STC_REBOL_TAG);
	Gura_AssignWxValue(STC_REBOL_FILE);
	Gura_AssignWxValue(STC_REBOL_EMAIL);
	Gura_AssignWxValue(STC_REBOL_URL);
	Gura_AssignWxValue(STC_REBOL_DATE);
	Gura_AssignWxValue(STC_REBOL_TIME);
	Gura_AssignWxValue(STC_REBOL_IDENTIFIER);
	Gura_AssignWxValue(STC_REBOL_WORD);
	Gura_AssignWxValue(STC_REBOL_WORD2);
	Gura_AssignWxValue(STC_REBOL_WORD3);
	Gura_AssignWxValue(STC_REBOL_WORD4);
	Gura_AssignWxValue(STC_REBOL_WORD5);
	Gura_AssignWxValue(STC_REBOL_WORD6);
	Gura_AssignWxValue(STC_REBOL_WORD7);
	Gura_AssignWxValue(STC_REBOL_WORD8);
	Gura_AssignWxValue(STC_SQL_DEFAULT);
	Gura_AssignWxValue(STC_SQL_COMMENT);
	Gura_AssignWxValue(STC_SQL_COMMENTLINE);
	Gura_AssignWxValue(STC_SQL_COMMENTDOC);
	Gura_AssignWxValue(STC_SQL_NUMBER);
	Gura_AssignWxValue(STC_SQL_WORD);
	Gura_AssignWxValue(STC_SQL_STRING);
	Gura_AssignWxValue(STC_SQL_CHARACTER);
	Gura_AssignWxValue(STC_SQL_SQLPLUS);
	Gura_AssignWxValue(STC_SQL_SQLPLUS_PROMPT);
	Gura_AssignWxValue(STC_SQL_OPERATOR);
	Gura_AssignWxValue(STC_SQL_IDENTIFIER);
	Gura_AssignWxValue(STC_SQL_SQLPLUS_COMMENT);
	Gura_AssignWxValue(STC_SQL_COMMENTLINEDOC);
	Gura_AssignWxValue(STC_SQL_WORD2);
	Gura_AssignWxValue(STC_SQL_COMMENTDOCKEYWORD);
	Gura_AssignWxValue(STC_SQL_COMMENTDOCKEYWORDERROR);
	Gura_AssignWxValue(STC_SQL_USER1);
	Gura_AssignWxValue(STC_SQL_USER2);
	Gura_AssignWxValue(STC_SQL_USER3);
	Gura_AssignWxValue(STC_SQL_USER4);
	Gura_AssignWxValue(STC_SQL_QUOTEDIDENTIFIER);
	Gura_AssignWxValue(STC_ST_DEFAULT);
	Gura_AssignWxValue(STC_ST_STRING);
	Gura_AssignWxValue(STC_ST_NUMBER);
	Gura_AssignWxValue(STC_ST_COMMENT);
	Gura_AssignWxValue(STC_ST_SYMBOL);
	Gura_AssignWxValue(STC_ST_BINARY);
	Gura_AssignWxValue(STC_ST_BOOL);
	Gura_AssignWxValue(STC_ST_SELF);
	Gura_AssignWxValue(STC_ST_SUPER);
	Gura_AssignWxValue(STC_ST_NIL);
	Gura_AssignWxValue(STC_ST_GLOBAL);
	Gura_AssignWxValue(STC_ST_RETURN);
	Gura_AssignWxValue(STC_ST_SPECIAL);
	Gura_AssignWxValue(STC_ST_KWSEND);
	Gura_AssignWxValue(STC_ST_ASSIGN);
	Gura_AssignWxValue(STC_ST_CHARACTER);
	Gura_AssignWxValue(STC_ST_SPEC_SEL);
	Gura_AssignWxValue(STC_FS_DEFAULT);
	Gura_AssignWxValue(STC_FS_COMMENT);
	Gura_AssignWxValue(STC_FS_COMMENTLINE);
	Gura_AssignWxValue(STC_FS_COMMENTDOC);
	Gura_AssignWxValue(STC_FS_COMMENTLINEDOC);
	Gura_AssignWxValue(STC_FS_COMMENTDOCKEYWORD);
	Gura_AssignWxValue(STC_FS_COMMENTDOCKEYWORDERROR);
	Gura_AssignWxValue(STC_FS_KEYWORD);
	Gura_AssignWxValue(STC_FS_KEYWORD2);
	Gura_AssignWxValue(STC_FS_KEYWORD3);
	Gura_AssignWxValue(STC_FS_KEYWORD4);
	Gura_AssignWxValue(STC_FS_NUMBER);
	Gura_AssignWxValue(STC_FS_STRING);
	Gura_AssignWxValue(STC_FS_PREPROCESSOR);
	Gura_AssignWxValue(STC_FS_OPERATOR);
	Gura_AssignWxValue(STC_FS_IDENTIFIER);
	Gura_AssignWxValue(STC_FS_DATE);
	Gura_AssignWxValue(STC_FS_STRINGEOL);
	Gura_AssignWxValue(STC_FS_CONSTANT);
	Gura_AssignWxValue(STC_FS_WORDOPERATOR);
	Gura_AssignWxValue(STC_FS_DISABLEDCODE);
	Gura_AssignWxValue(STC_FS_DEFAULT_C);
	Gura_AssignWxValue(STC_FS_COMMENTDOC_C);
	Gura_AssignWxValue(STC_FS_COMMENTLINEDOC_C);
	Gura_AssignWxValue(STC_FS_KEYWORD_C);
	Gura_AssignWxValue(STC_FS_KEYWORD2_C);
	Gura_AssignWxValue(STC_FS_NUMBER_C);
	Gura_AssignWxValue(STC_FS_STRING_C);
	Gura_AssignWxValue(STC_FS_PREPROCESSOR_C);
	Gura_AssignWxValue(STC_FS_OPERATOR_C);
	Gura_AssignWxValue(STC_FS_IDENTIFIER_C);
	Gura_AssignWxValue(STC_FS_STRINGEOL_C);
	Gura_AssignWxValue(STC_CSOUND_DEFAULT);
	Gura_AssignWxValue(STC_CSOUND_COMMENT);
	Gura_AssignWxValue(STC_CSOUND_NUMBER);
	Gura_AssignWxValue(STC_CSOUND_OPERATOR);
	Gura_AssignWxValue(STC_CSOUND_INSTR);
	Gura_AssignWxValue(STC_CSOUND_IDENTIFIER);
	Gura_AssignWxValue(STC_CSOUND_OPCODE);
	Gura_AssignWxValue(STC_CSOUND_HEADERSTMT);
	Gura_AssignWxValue(STC_CSOUND_USERKEYWORD);
	Gura_AssignWxValue(STC_CSOUND_COMMENTBLOCK);
	Gura_AssignWxValue(STC_CSOUND_PARAM);
	Gura_AssignWxValue(STC_CSOUND_ARATE_VAR);
	Gura_AssignWxValue(STC_CSOUND_KRATE_VAR);
	Gura_AssignWxValue(STC_CSOUND_IRATE_VAR);
	Gura_AssignWxValue(STC_CSOUND_GLOBAL_VAR);
	Gura_AssignWxValue(STC_CSOUND_STRINGEOL);
	Gura_AssignWxValue(STC_INNO_DEFAULT);
	Gura_AssignWxValue(STC_INNO_COMMENT);
	Gura_AssignWxValue(STC_INNO_KEYWORD);
	Gura_AssignWxValue(STC_INNO_PARAMETER);
	Gura_AssignWxValue(STC_INNO_SECTION);
	Gura_AssignWxValue(STC_INNO_PREPROC);
	Gura_AssignWxValue(STC_INNO_INLINE_EXPANSION);
	Gura_AssignWxValue(STC_INNO_COMMENT_PASCAL);
	Gura_AssignWxValue(STC_INNO_KEYWORD_PASCAL);
	Gura_AssignWxValue(STC_INNO_KEYWORD_USER);
	Gura_AssignWxValue(STC_INNO_STRING_DOUBLE);
	Gura_AssignWxValue(STC_INNO_STRING_SINGLE);
	Gura_AssignWxValue(STC_INNO_IDENTIFIER);
	Gura_AssignWxValue(STC_OPAL_SPACE);
	Gura_AssignWxValue(STC_OPAL_COMMENT_BLOCK);
	Gura_AssignWxValue(STC_OPAL_COMMENT_LINE);
	Gura_AssignWxValue(STC_OPAL_INTEGER);
	Gura_AssignWxValue(STC_OPAL_KEYWORD);
	Gura_AssignWxValue(STC_OPAL_SORT);
	Gura_AssignWxValue(STC_OPAL_STRING);
	Gura_AssignWxValue(STC_OPAL_PAR);
	Gura_AssignWxValue(STC_OPAL_BOOL_CONST);
	Gura_AssignWxValue(STC_OPAL_DEFAULT);
	Gura_AssignWxValue(STC_SPICE_DEFAULT);
	Gura_AssignWxValue(STC_SPICE_IDENTIFIER);
	Gura_AssignWxValue(STC_SPICE_KEYWORD);
	Gura_AssignWxValue(STC_SPICE_KEYWORD2);
	Gura_AssignWxValue(STC_SPICE_KEYWORD3);
	Gura_AssignWxValue(STC_SPICE_NUMBER);
	Gura_AssignWxValue(STC_SPICE_DELIMITER);
	Gura_AssignWxValue(STC_SPICE_VALUE);
	Gura_AssignWxValue(STC_SPICE_COMMENTLINE);
	Gura_AssignWxValue(STC_CMAKE_DEFAULT);
	Gura_AssignWxValue(STC_CMAKE_COMMENT);
	Gura_AssignWxValue(STC_CMAKE_STRINGDQ);
	Gura_AssignWxValue(STC_CMAKE_STRINGLQ);
	Gura_AssignWxValue(STC_CMAKE_STRINGRQ);
	Gura_AssignWxValue(STC_CMAKE_COMMANDS);
	Gura_AssignWxValue(STC_CMAKE_PARAMETERS);
	Gura_AssignWxValue(STC_CMAKE_VARIABLE);
	Gura_AssignWxValue(STC_CMAKE_USERDEFINED);
	Gura_AssignWxValue(STC_CMAKE_WHILEDEF);
	Gura_AssignWxValue(STC_CMAKE_FOREACHDEF);
	Gura_AssignWxValue(STC_CMAKE_IFDEFINEDEF);
	Gura_AssignWxValue(STC_CMAKE_MACRODEF);
	Gura_AssignWxValue(STC_CMAKE_STRINGVAR);
	Gura_AssignWxValue(STC_CMAKE_NUMBER);
	Gura_AssignWxValue(STC_GAP_DEFAULT);
	Gura_AssignWxValue(STC_GAP_IDENTIFIER);
	Gura_AssignWxValue(STC_GAP_KEYWORD);
	Gura_AssignWxValue(STC_GAP_KEYWORD2);
	Gura_AssignWxValue(STC_GAP_KEYWORD3);
	Gura_AssignWxValue(STC_GAP_KEYWORD4);
	Gura_AssignWxValue(STC_GAP_STRING);
	Gura_AssignWxValue(STC_GAP_CHAR);
	Gura_AssignWxValue(STC_GAP_OPERATOR);
	Gura_AssignWxValue(STC_GAP_COMMENT);
	Gura_AssignWxValue(STC_GAP_NUMBER);
	Gura_AssignWxValue(STC_GAP_STRINGEOL);
	Gura_AssignWxValue(STC_PLM_DEFAULT);
	Gura_AssignWxValue(STC_PLM_COMMENT);
	Gura_AssignWxValue(STC_PLM_STRING);
	Gura_AssignWxValue(STC_PLM_NUMBER);
	Gura_AssignWxValue(STC_PLM_IDENTIFIER);
	Gura_AssignWxValue(STC_PLM_OPERATOR);
	Gura_AssignWxValue(STC_PLM_CONTROL);
	Gura_AssignWxValue(STC_PLM_KEYWORD);
	Gura_AssignWxValue(STC_4GL_DEFAULT);
	Gura_AssignWxValue(STC_4GL_NUMBER);
	Gura_AssignWxValue(STC_4GL_WORD);
	Gura_AssignWxValue(STC_4GL_STRING);
	Gura_AssignWxValue(STC_4GL_CHARACTER);
	Gura_AssignWxValue(STC_4GL_PREPROCESSOR);
	Gura_AssignWxValue(STC_4GL_OPERATOR);
	Gura_AssignWxValue(STC_4GL_IDENTIFIER);
	Gura_AssignWxValue(STC_4GL_BLOCK);
	Gura_AssignWxValue(STC_4GL_END);
	Gura_AssignWxValue(STC_4GL_COMMENT1);
	Gura_AssignWxValue(STC_4GL_COMMENT2);
	Gura_AssignWxValue(STC_4GL_COMMENT3);
	Gura_AssignWxValue(STC_4GL_COMMENT4);
	Gura_AssignWxValue(STC_4GL_COMMENT5);
	Gura_AssignWxValue(STC_4GL_COMMENT6);
	Gura_AssignWxValue(STC_4GL_DEFAULT_);
	Gura_AssignWxValue(STC_4GL_NUMBER_);
	Gura_AssignWxValue(STC_4GL_WORD_);
	Gura_AssignWxValue(STC_4GL_STRING_);
	Gura_AssignWxValue(STC_4GL_CHARACTER_);
	Gura_AssignWxValue(STC_4GL_PREPROCESSOR_);
	Gura_AssignWxValue(STC_4GL_OPERATOR_);
	Gura_AssignWxValue(STC_4GL_IDENTIFIER_);
	Gura_AssignWxValue(STC_4GL_BLOCK_);
	Gura_AssignWxValue(STC_4GL_END_);
	Gura_AssignWxValue(STC_4GL_COMMENT1_);
	Gura_AssignWxValue(STC_4GL_COMMENT2_);
	Gura_AssignWxValue(STC_4GL_COMMENT3_);
	Gura_AssignWxValue(STC_4GL_COMMENT4_);
	Gura_AssignWxValue(STC_4GL_COMMENT5_);
	Gura_AssignWxValue(STC_4GL_COMMENT6_);
	Gura_AssignWxValue(STC_ABAQUS_DEFAULT);
	Gura_AssignWxValue(STC_ABAQUS_COMMENT);
	Gura_AssignWxValue(STC_ABAQUS_COMMENTBLOCK);
	Gura_AssignWxValue(STC_ABAQUS_NUMBER);
	Gura_AssignWxValue(STC_ABAQUS_STRING);
	Gura_AssignWxValue(STC_ABAQUS_OPERATOR);
	Gura_AssignWxValue(STC_ABAQUS_WORD);
	Gura_AssignWxValue(STC_ABAQUS_PROCESSOR);
	Gura_AssignWxValue(STC_ABAQUS_COMMAND);
	Gura_AssignWxValue(STC_ABAQUS_SLASHCOMMAND);
	Gura_AssignWxValue(STC_ABAQUS_STARCOMMAND);
	Gura_AssignWxValue(STC_ABAQUS_ARGUMENT);
	Gura_AssignWxValue(STC_ABAQUS_FUNCTION);
	Gura_AssignWxValue(STC_ASY_DEFAULT);
	Gura_AssignWxValue(STC_ASY_COMMENT);
	Gura_AssignWxValue(STC_ASY_COMMENTLINE);
	Gura_AssignWxValue(STC_ASY_NUMBER);
	Gura_AssignWxValue(STC_ASY_WORD);
	Gura_AssignWxValue(STC_ASY_STRING);
	Gura_AssignWxValue(STC_ASY_CHARACTER);
	Gura_AssignWxValue(STC_ASY_OPERATOR);
	Gura_AssignWxValue(STC_ASY_IDENTIFIER);
	Gura_AssignWxValue(STC_ASY_STRINGEOL);
	Gura_AssignWxValue(STC_ASY_COMMENTLINEDOC);
	Gura_AssignWxValue(STC_ASY_WORD2);
	Gura_AssignWxValue(STC_R_DEFAULT);
	Gura_AssignWxValue(STC_R_COMMENT);
	Gura_AssignWxValue(STC_R_KWORD);
	Gura_AssignWxValue(STC_R_BASEKWORD);
	Gura_AssignWxValue(STC_R_OTHERKWORD);
	Gura_AssignWxValue(STC_R_NUMBER);
	Gura_AssignWxValue(STC_R_STRING);
	Gura_AssignWxValue(STC_R_STRING2);
	Gura_AssignWxValue(STC_R_OPERATOR);
	Gura_AssignWxValue(STC_R_IDENTIFIER);
	Gura_AssignWxValue(STC_R_INFIX);
	Gura_AssignWxValue(STC_R_INFIXEOL);
	Gura_AssignWxValue(STC_MAGIK_DEFAULT);
	Gura_AssignWxValue(STC_MAGIK_COMMENT);
	Gura_AssignWxValue(STC_MAGIK_HYPER_COMMENT);
	Gura_AssignWxValue(STC_MAGIK_STRING);
	Gura_AssignWxValue(STC_MAGIK_CHARACTER);
	Gura_AssignWxValue(STC_MAGIK_NUMBER);
	Gura_AssignWxValue(STC_MAGIK_IDENTIFIER);
	Gura_AssignWxValue(STC_MAGIK_OPERATOR);
	Gura_AssignWxValue(STC_MAGIK_FLOW);
	Gura_AssignWxValue(STC_MAGIK_CONTAINER);
	Gura_AssignWxValue(STC_MAGIK_BRACKET_BLOCK);
	Gura_AssignWxValue(STC_MAGIK_BRACE_BLOCK);
	Gura_AssignWxValue(STC_MAGIK_SQBRACKET_BLOCK);
	Gura_AssignWxValue(STC_MAGIK_UNKNOWN_KEYWORD);
	Gura_AssignWxValue(STC_MAGIK_KEYWORD);
	Gura_AssignWxValue(STC_MAGIK_PRAGMA);
	Gura_AssignWxValue(STC_MAGIK_SYMBOL);
	Gura_AssignWxValue(STC_POWERSHELL_DEFAULT);
	Gura_AssignWxValue(STC_POWERSHELL_COMMENT);
	Gura_AssignWxValue(STC_POWERSHELL_STRING);
	Gura_AssignWxValue(STC_POWERSHELL_CHARACTER);
	Gura_AssignWxValue(STC_POWERSHELL_NUMBER);
	Gura_AssignWxValue(STC_POWERSHELL_VARIABLE);
	Gura_AssignWxValue(STC_POWERSHELL_OPERATOR);
	Gura_AssignWxValue(STC_POWERSHELL_IDENTIFIER);
	Gura_AssignWxValue(STC_POWERSHELL_KEYWORD);
	Gura_AssignWxValue(STC_POWERSHELL_CMDLET);
	Gura_AssignWxValue(STC_POWERSHELL_ALIAS);
	Gura_AssignWxValue(STC_POWERSHELL_FUNCTION);
	Gura_AssignWxValue(STC_POWERSHELL_USER1);
	Gura_AssignWxValue(STC_POWERSHELL_COMMENTSTREAM);
	Gura_AssignWxValue(STC_MYSQL_DEFAULT);
	Gura_AssignWxValue(STC_MYSQL_COMMENT);
	Gura_AssignWxValue(STC_MYSQL_COMMENTLINE);
	Gura_AssignWxValue(STC_MYSQL_VARIABLE);
	Gura_AssignWxValue(STC_MYSQL_SYSTEMVARIABLE);
	Gura_AssignWxValue(STC_MYSQL_KNOWNSYSTEMVARIABLE);
	Gura_AssignWxValue(STC_MYSQL_NUMBER);
	Gura_AssignWxValue(STC_MYSQL_MAJORKEYWORD);
	Gura_AssignWxValue(STC_MYSQL_KEYWORD);
	Gura_AssignWxValue(STC_MYSQL_DATABASEOBJECT);
	Gura_AssignWxValue(STC_MYSQL_PROCEDUREKEYWORD);
	Gura_AssignWxValue(STC_MYSQL_STRING);
	Gura_AssignWxValue(STC_MYSQL_SQSTRING);
	Gura_AssignWxValue(STC_MYSQL_DQSTRING);
	Gura_AssignWxValue(STC_MYSQL_OPERATOR);
	Gura_AssignWxValue(STC_MYSQL_FUNCTION);
	Gura_AssignWxValue(STC_MYSQL_IDENTIFIER);
	Gura_AssignWxValue(STC_MYSQL_QUOTEDIDENTIFIER);
	Gura_AssignWxValue(STC_MYSQL_USER1);
	Gura_AssignWxValue(STC_MYSQL_USER2);
	Gura_AssignWxValue(STC_MYSQL_USER3);
	Gura_AssignWxValue(STC_MYSQL_HIDDENCOMMAND);
	Gura_AssignWxValue(STC_PO_DEFAULT);
	Gura_AssignWxValue(STC_PO_COMMENT);
	Gura_AssignWxValue(STC_PO_MSGID);
	Gura_AssignWxValue(STC_PO_MSGID_TEXT);
	Gura_AssignWxValue(STC_PO_MSGSTR);
	Gura_AssignWxValue(STC_PO_MSGSTR_TEXT);
	Gura_AssignWxValue(STC_PO_MSGCTXT);
	Gura_AssignWxValue(STC_PO_MSGCTXT_TEXT);
	Gura_AssignWxValue(STC_PO_FUZZY);
	Gura_AssignWxValue(STC_PAS_DEFAULT);
	Gura_AssignWxValue(STC_PAS_IDENTIFIER);
	Gura_AssignWxValue(STC_PAS_COMMENT);
	Gura_AssignWxValue(STC_PAS_COMMENT2);
	Gura_AssignWxValue(STC_PAS_COMMENTLINE);
	Gura_AssignWxValue(STC_PAS_PREPROCESSOR);
	Gura_AssignWxValue(STC_PAS_PREPROCESSOR2);
	Gura_AssignWxValue(STC_PAS_NUMBER);
	Gura_AssignWxValue(STC_PAS_HEXNUMBER);
	Gura_AssignWxValue(STC_PAS_WORD);
	Gura_AssignWxValue(STC_PAS_STRING);
	Gura_AssignWxValue(STC_PAS_STRINGEOL);
	Gura_AssignWxValue(STC_PAS_CHARACTER);
	Gura_AssignWxValue(STC_PAS_OPERATOR);
	Gura_AssignWxValue(STC_PAS_ASM);
	Gura_AssignWxValue(STC_SORCUS_DEFAULT);
	Gura_AssignWxValue(STC_SORCUS_COMMAND);
	Gura_AssignWxValue(STC_SORCUS_PARAMETER);
	Gura_AssignWxValue(STC_SORCUS_COMMENTLINE);
	Gura_AssignWxValue(STC_SORCUS_STRING);
	Gura_AssignWxValue(STC_SORCUS_STRINGEOL);
	Gura_AssignWxValue(STC_SORCUS_IDENTIFIER);
	Gura_AssignWxValue(STC_SORCUS_OPERATOR);
	Gura_AssignWxValue(STC_SORCUS_NUMBER);
	Gura_AssignWxValue(STC_SORCUS_CONSTANT);
	Gura_AssignWxValue(STC_POWERPRO_DEFAULT);
	Gura_AssignWxValue(STC_POWERPRO_COMMENTBLOCK);
	Gura_AssignWxValue(STC_POWERPRO_COMMENTLINE);
	Gura_AssignWxValue(STC_POWERPRO_NUMBER);
	Gura_AssignWxValue(STC_POWERPRO_WORD);
	Gura_AssignWxValue(STC_POWERPRO_WORD2);
	Gura_AssignWxValue(STC_POWERPRO_WORD3);
	Gura_AssignWxValue(STC_POWERPRO_WORD4);
	Gura_AssignWxValue(STC_POWERPRO_DOUBLEQUOTEDSTRING);
	Gura_AssignWxValue(STC_POWERPRO_SINGLEQUOTEDSTRING);
	Gura_AssignWxValue(STC_POWERPRO_LINECONTINUE);
	Gura_AssignWxValue(STC_POWERPRO_OPERATOR);
	Gura_AssignWxValue(STC_POWERPRO_IDENTIFIER);
	Gura_AssignWxValue(STC_POWERPRO_STRINGEOL);
	Gura_AssignWxValue(STC_POWERPRO_VERBATIM);
	Gura_AssignWxValue(STC_POWERPRO_ALTQUOTE);
	Gura_AssignWxValue(STC_POWERPRO_FUNCTION);
	Gura_AssignWxValue(STC_SML_DEFAULT);
	Gura_AssignWxValue(STC_SML_IDENTIFIER);
	Gura_AssignWxValue(STC_SML_TAGNAME);
	Gura_AssignWxValue(STC_SML_KEYWORD);
	Gura_AssignWxValue(STC_SML_KEYWORD2);
	Gura_AssignWxValue(STC_SML_KEYWORD3);
	Gura_AssignWxValue(STC_SML_LINENUM);
	Gura_AssignWxValue(STC_SML_OPERATOR);
	Gura_AssignWxValue(STC_SML_NUMBER);
	Gura_AssignWxValue(STC_SML_CHAR);
	Gura_AssignWxValue(STC_SML_STRING);
	Gura_AssignWxValue(STC_SML_COMMENT);
	Gura_AssignWxValue(STC_SML_COMMENT1);
	Gura_AssignWxValue(STC_SML_COMMENT2);
	Gura_AssignWxValue(STC_SML_COMMENT3);
	Gura_AssignWxValue(STC_MARKDOWN_DEFAULT);
	Gura_AssignWxValue(STC_MARKDOWN_LINE_BEGIN);
	Gura_AssignWxValue(STC_MARKDOWN_STRONG1);
	Gura_AssignWxValue(STC_MARKDOWN_STRONG2);
	Gura_AssignWxValue(STC_MARKDOWN_EM1);
	Gura_AssignWxValue(STC_MARKDOWN_EM2);
	Gura_AssignWxValue(STC_MARKDOWN_HEADER1);
	Gura_AssignWxValue(STC_MARKDOWN_HEADER2);
	Gura_AssignWxValue(STC_MARKDOWN_HEADER3);
	Gura_AssignWxValue(STC_MARKDOWN_HEADER4);
	Gura_AssignWxValue(STC_MARKDOWN_HEADER5);
	Gura_AssignWxValue(STC_MARKDOWN_HEADER6);
	Gura_AssignWxValue(STC_MARKDOWN_PRECHAR);
	Gura_AssignWxValue(STC_MARKDOWN_ULIST_ITEM);
	Gura_AssignWxValue(STC_MARKDOWN_OLIST_ITEM);
	Gura_AssignWxValue(STC_MARKDOWN_BLOCKQUOTE);
	Gura_AssignWxValue(STC_MARKDOWN_STRIKEOUT);
	Gura_AssignWxValue(STC_MARKDOWN_HRULE);
	Gura_AssignWxValue(STC_MARKDOWN_LINK);
	Gura_AssignWxValue(STC_MARKDOWN_CODE);
	Gura_AssignWxValue(STC_MARKDOWN_CODE2);
	Gura_AssignWxValue(STC_MARKDOWN_CODEBK);
	Gura_AssignWxValue(STC_TXT2TAGS_DEFAULT);
	Gura_AssignWxValue(STC_TXT2TAGS_LINE_BEGIN);
	Gura_AssignWxValue(STC_TXT2TAGS_STRONG1);
	Gura_AssignWxValue(STC_TXT2TAGS_STRONG2);
	Gura_AssignWxValue(STC_TXT2TAGS_EM1);
	Gura_AssignWxValue(STC_TXT2TAGS_EM2);
	Gura_AssignWxValue(STC_TXT2TAGS_HEADER1);
	Gura_AssignWxValue(STC_TXT2TAGS_HEADER2);
	Gura_AssignWxValue(STC_TXT2TAGS_HEADER3);
	Gura_AssignWxValue(STC_TXT2TAGS_HEADER4);
	Gura_AssignWxValue(STC_TXT2TAGS_HEADER5);
	Gura_AssignWxValue(STC_TXT2TAGS_HEADER6);
	Gura_AssignWxValue(STC_TXT2TAGS_PRECHAR);
	Gura_AssignWxValue(STC_TXT2TAGS_ULIST_ITEM);
	Gura_AssignWxValue(STC_TXT2TAGS_OLIST_ITEM);
	Gura_AssignWxValue(STC_TXT2TAGS_BLOCKQUOTE);
	Gura_AssignWxValue(STC_TXT2TAGS_STRIKEOUT);
	Gura_AssignWxValue(STC_TXT2TAGS_HRULE);
	Gura_AssignWxValue(STC_TXT2TAGS_LINK);
	Gura_AssignWxValue(STC_TXT2TAGS_CODE);
	Gura_AssignWxValue(STC_TXT2TAGS_CODE2);
	Gura_AssignWxValue(STC_TXT2TAGS_CODEBK);
	Gura_AssignWxValue(STC_TXT2TAGS_COMMENT);
	Gura_AssignWxValue(STC_TXT2TAGS_OPTION);
	Gura_AssignWxValue(STC_TXT2TAGS_PREPROC);
	Gura_AssignWxValue(STC_TXT2TAGS_POSTPROC);
	Gura_AssignWxValue(STC_A68K_DEFAULT);
	Gura_AssignWxValue(STC_A68K_COMMENT);
	Gura_AssignWxValue(STC_A68K_NUMBER_DEC);
	Gura_AssignWxValue(STC_A68K_NUMBER_BIN);
	Gura_AssignWxValue(STC_A68K_NUMBER_HEX);
	Gura_AssignWxValue(STC_A68K_STRING1);
	Gura_AssignWxValue(STC_A68K_OPERATOR);
	Gura_AssignWxValue(STC_A68K_CPUINSTRUCTION);
	Gura_AssignWxValue(STC_A68K_EXTINSTRUCTION);
	Gura_AssignWxValue(STC_A68K_REGISTER);
	Gura_AssignWxValue(STC_A68K_DIRECTIVE);
	Gura_AssignWxValue(STC_A68K_MACRO_ARG);
	Gura_AssignWxValue(STC_A68K_LABEL);
	Gura_AssignWxValue(STC_A68K_STRING2);
	Gura_AssignWxValue(STC_A68K_IDENTIFIER);
	Gura_AssignWxValue(STC_A68K_MACRO_DECLARATION);
	Gura_AssignWxValue(STC_A68K_COMMENT_WORD);
	Gura_AssignWxValue(STC_A68K_COMMENT_SPECIAL);
	Gura_AssignWxValue(STC_A68K_COMMENT_DOXYGEN);
	Gura_AssignWxValue(STC_MODULA_DEFAULT);
	Gura_AssignWxValue(STC_MODULA_COMMENT);
	Gura_AssignWxValue(STC_MODULA_DOXYCOMM);
	Gura_AssignWxValue(STC_MODULA_DOXYKEY);
	Gura_AssignWxValue(STC_MODULA_KEYWORD);
	Gura_AssignWxValue(STC_MODULA_RESERVED);
	Gura_AssignWxValue(STC_MODULA_NUMBER);
	Gura_AssignWxValue(STC_MODULA_BASENUM);
	Gura_AssignWxValue(STC_MODULA_FLOAT);
	Gura_AssignWxValue(STC_MODULA_STRING);
	Gura_AssignWxValue(STC_MODULA_STRSPEC);
	Gura_AssignWxValue(STC_MODULA_CHAR);
	Gura_AssignWxValue(STC_MODULA_CHARSPEC);
	Gura_AssignWxValue(STC_MODULA_PROC);
	Gura_AssignWxValue(STC_MODULA_PRAGMA);
	Gura_AssignWxValue(STC_MODULA_PRGKEY);
	Gura_AssignWxValue(STC_MODULA_OPERATOR);
	Gura_AssignWxValue(STC_MODULA_BADSTR);
	Gura_AssignWxValue(STC_COFFEESCRIPT_DEFAULT);
	Gura_AssignWxValue(STC_COFFEESCRIPT_COMMENT);
	Gura_AssignWxValue(STC_COFFEESCRIPT_COMMENTLINE);
	Gura_AssignWxValue(STC_COFFEESCRIPT_COMMENTDOC);
	Gura_AssignWxValue(STC_COFFEESCRIPT_NUMBER);
	Gura_AssignWxValue(STC_COFFEESCRIPT_WORD);
	Gura_AssignWxValue(STC_COFFEESCRIPT_STRING);
	Gura_AssignWxValue(STC_COFFEESCRIPT_CHARACTER);
	Gura_AssignWxValue(STC_COFFEESCRIPT_UUID);
	Gura_AssignWxValue(STC_COFFEESCRIPT_PREPROCESSOR);
	Gura_AssignWxValue(STC_COFFEESCRIPT_OPERATOR);
	Gura_AssignWxValue(STC_COFFEESCRIPT_IDENTIFIER);
	Gura_AssignWxValue(STC_COFFEESCRIPT_STRINGEOL);
	Gura_AssignWxValue(STC_COFFEESCRIPT_VERBATIM);
	Gura_AssignWxValue(STC_COFFEESCRIPT_REGEX);
	Gura_AssignWxValue(STC_COFFEESCRIPT_COMMENTLINEDOC);
	Gura_AssignWxValue(STC_COFFEESCRIPT_WORD2);
	Gura_AssignWxValue(STC_COFFEESCRIPT_COMMENTDOCKEYWORD);
	Gura_AssignWxValue(STC_COFFEESCRIPT_COMMENTDOCKEYWORDERROR);
	Gura_AssignWxValue(STC_COFFEESCRIPT_GLOBALCLASS);
	Gura_AssignWxValue(STC_COFFEESCRIPT_STRINGRAW);
	Gura_AssignWxValue(STC_COFFEESCRIPT_TRIPLEVERBATIM);
	Gura_AssignWxValue(STC_COFFEESCRIPT_HASHQUOTEDSTRING);
	Gura_AssignWxValue(STC_COFFEESCRIPT_COMMENTBLOCK);
	Gura_AssignWxValue(STC_COFFEESCRIPT_VERBOSE_REGEX);
	Gura_AssignWxValue(STC_COFFEESCRIPT_VERBOSE_REGEX_COMMENT);
	Gura_AssignWxValue(STC_AVS_DEFAULT);
	Gura_AssignWxValue(STC_AVS_COMMENTBLOCK);
	Gura_AssignWxValue(STC_AVS_COMMENTBLOCKN);
	Gura_AssignWxValue(STC_AVS_COMMENTLINE);
	Gura_AssignWxValue(STC_AVS_NUMBER);
	Gura_AssignWxValue(STC_AVS_OPERATOR);
	Gura_AssignWxValue(STC_AVS_IDENTIFIER);
	Gura_AssignWxValue(STC_AVS_STRING);
	Gura_AssignWxValue(STC_AVS_TRIPLESTRING);
	Gura_AssignWxValue(STC_AVS_KEYWORD);
	Gura_AssignWxValue(STC_AVS_FILTER);
	Gura_AssignWxValue(STC_AVS_PLUGIN);
	Gura_AssignWxValue(STC_AVS_FUNCTION);
	Gura_AssignWxValue(STC_AVS_CLIPPROP);
	Gura_AssignWxValue(STC_AVS_USERDFN);
	Gura_AssignWxValue(STC_ECL_DEFAULT);
	Gura_AssignWxValue(STC_ECL_COMMENT);
	Gura_AssignWxValue(STC_ECL_COMMENTLINE);
	Gura_AssignWxValue(STC_ECL_NUMBER);
	Gura_AssignWxValue(STC_ECL_STRING);
	Gura_AssignWxValue(STC_ECL_WORD0);
	Gura_AssignWxValue(STC_ECL_OPERATOR);
	Gura_AssignWxValue(STC_ECL_CHARACTER);
	Gura_AssignWxValue(STC_ECL_UUID);
	Gura_AssignWxValue(STC_ECL_PREPROCESSOR);
	Gura_AssignWxValue(STC_ECL_UNKNOWN);
	Gura_AssignWxValue(STC_ECL_IDENTIFIER);
	Gura_AssignWxValue(STC_ECL_STRINGEOL);
	Gura_AssignWxValue(STC_ECL_VERBATIM);
	Gura_AssignWxValue(STC_ECL_REGEX);
	Gura_AssignWxValue(STC_ECL_COMMENTLINEDOC);
	Gura_AssignWxValue(STC_ECL_WORD1);
	Gura_AssignWxValue(STC_ECL_COMMENTDOCKEYWORD);
	Gura_AssignWxValue(STC_ECL_COMMENTDOCKEYWORDERROR);
	Gura_AssignWxValue(STC_ECL_WORD2);
	Gura_AssignWxValue(STC_ECL_WORD3);
	Gura_AssignWxValue(STC_ECL_WORD4);
	Gura_AssignWxValue(STC_ECL_WORD5);
	Gura_AssignWxValue(STC_ECL_COMMENTDOC);
	Gura_AssignWxValue(STC_ECL_ADDED);
	Gura_AssignWxValue(STC_ECL_DELETED);
	Gura_AssignWxValue(STC_ECL_CHANGED);
	Gura_AssignWxValue(STC_ECL_MOVED);
	Gura_AssignWxValue(STC_OSCRIPT_DEFAULT);
	Gura_AssignWxValue(STC_OSCRIPT_LINE_COMMENT);
	Gura_AssignWxValue(STC_OSCRIPT_BLOCK_COMMENT);
	Gura_AssignWxValue(STC_OSCRIPT_DOC_COMMENT);
	Gura_AssignWxValue(STC_OSCRIPT_PREPROCESSOR);
	Gura_AssignWxValue(STC_OSCRIPT_NUMBER);
	Gura_AssignWxValue(STC_OSCRIPT_SINGLEQUOTE_STRING);
	Gura_AssignWxValue(STC_OSCRIPT_DOUBLEQUOTE_STRING);
	Gura_AssignWxValue(STC_OSCRIPT_CONSTANT);
	Gura_AssignWxValue(STC_OSCRIPT_IDENTIFIER);
	Gura_AssignWxValue(STC_OSCRIPT_GLOBAL);
	Gura_AssignWxValue(STC_OSCRIPT_KEYWORD);
	Gura_AssignWxValue(STC_OSCRIPT_OPERATOR);
	Gura_AssignWxValue(STC_OSCRIPT_LABEL);
	Gura_AssignWxValue(STC_OSCRIPT_TYPE);
	Gura_AssignWxValue(STC_OSCRIPT_FUNCTION);
	Gura_AssignWxValue(STC_OSCRIPT_OBJECT);
	Gura_AssignWxValue(STC_OSCRIPT_PROPERTY);
	Gura_AssignWxValue(STC_OSCRIPT_METHOD);
	Gura_AssignWxValue(STC_VISUALPROLOG_DEFAULT);
	Gura_AssignWxValue(STC_VISUALPROLOG_KEY_MAJOR);
	Gura_AssignWxValue(STC_VISUALPROLOG_KEY_MINOR);
	Gura_AssignWxValue(STC_VISUALPROLOG_KEY_DIRECTIVE);
	Gura_AssignWxValue(STC_VISUALPROLOG_COMMENT_BLOCK);
	Gura_AssignWxValue(STC_VISUALPROLOG_COMMENT_LINE);
	Gura_AssignWxValue(STC_VISUALPROLOG_COMMENT_KEY);
	Gura_AssignWxValue(STC_VISUALPROLOG_COMMENT_KEY_ERROR);
	Gura_AssignWxValue(STC_VISUALPROLOG_IDENTIFIER);
	Gura_AssignWxValue(STC_VISUALPROLOG_VARIABLE);
	Gura_AssignWxValue(STC_VISUALPROLOG_ANONYMOUS);
	Gura_AssignWxValue(STC_VISUALPROLOG_NUMBER);
	Gura_AssignWxValue(STC_VISUALPROLOG_OPERATOR);
	Gura_AssignWxValue(STC_VISUALPROLOG_CHARACTER);
	Gura_AssignWxValue(STC_VISUALPROLOG_CHARACTER_TOO_MANY);
	Gura_AssignWxValue(STC_VISUALPROLOG_CHARACTER_ESCAPE_ERROR);
	Gura_AssignWxValue(STC_VISUALPROLOG_STRING);
	Gura_AssignWxValue(STC_VISUALPROLOG_STRING_ESCAPE);
	Gura_AssignWxValue(STC_VISUALPROLOG_STRING_ESCAPE_ERROR);
	Gura_AssignWxValue(STC_VISUALPROLOG_STRING_EOL_OPEN);
	Gura_AssignWxValue(STC_VISUALPROLOG_STRING_VERBATIM);
	Gura_AssignWxValue(STC_VISUALPROLOG_STRING_VERBATIM_SPECIAL);
	Gura_AssignWxValue(STC_VISUALPROLOG_STRING_VERBATIM_EOL);
	Gura_AssignWxValue(STC_CMD_REDO);
	Gura_AssignWxValue(STC_CMD_SELECTALL);
	Gura_AssignWxValue(STC_CMD_UNDO);
	Gura_AssignWxValue(STC_CMD_CUT);
	Gura_AssignWxValue(STC_CMD_COPY);
	Gura_AssignWxValue(STC_CMD_PASTE);
	Gura_AssignWxValue(STC_CMD_CLEAR);
	Gura_AssignWxValue(STC_CMD_LINEDOWN);
	Gura_AssignWxValue(STC_CMD_LINEDOWNEXTEND);
	Gura_AssignWxValue(STC_CMD_LINEUP);
	Gura_AssignWxValue(STC_CMD_LINEUPEXTEND);
	Gura_AssignWxValue(STC_CMD_CHARLEFT);
	Gura_AssignWxValue(STC_CMD_CHARLEFTEXTEND);
	Gura_AssignWxValue(STC_CMD_CHARRIGHT);
	Gura_AssignWxValue(STC_CMD_CHARRIGHTEXTEND);
	Gura_AssignWxValue(STC_CMD_WORDLEFT);
	Gura_AssignWxValue(STC_CMD_WORDLEFTEXTEND);
	Gura_AssignWxValue(STC_CMD_WORDRIGHT);
	Gura_AssignWxValue(STC_CMD_WORDRIGHTEXTEND);
	Gura_AssignWxValue(STC_CMD_HOME);
	Gura_AssignWxValue(STC_CMD_HOMEEXTEND);
	Gura_AssignWxValue(STC_CMD_LINEEND);
	Gura_AssignWxValue(STC_CMD_LINEENDEXTEND);
	Gura_AssignWxValue(STC_CMD_DOCUMENTSTART);
	Gura_AssignWxValue(STC_CMD_DOCUMENTSTARTEXTEND);
	Gura_AssignWxValue(STC_CMD_DOCUMENTEND);
	Gura_AssignWxValue(STC_CMD_DOCUMENTENDEXTEND);
	Gura_AssignWxValue(STC_CMD_PAGEUP);
	Gura_AssignWxValue(STC_CMD_PAGEUPEXTEND);
	Gura_AssignWxValue(STC_CMD_PAGEDOWN);
	Gura_AssignWxValue(STC_CMD_PAGEDOWNEXTEND);
	Gura_AssignWxValue(STC_CMD_EDITTOGGLEOVERTYPE);
	Gura_AssignWxValue(STC_CMD_CANCEL);
	Gura_AssignWxValue(STC_CMD_DELETEBACK);
	Gura_AssignWxValue(STC_CMD_TAB);
	Gura_AssignWxValue(STC_CMD_BACKTAB);
	Gura_AssignWxValue(STC_CMD_NEWLINE);
	Gura_AssignWxValue(STC_CMD_FORMFEED);
	Gura_AssignWxValue(STC_CMD_VCHOME);
	Gura_AssignWxValue(STC_CMD_VCHOMEEXTEND);
	Gura_AssignWxValue(STC_CMD_ZOOMIN);
	Gura_AssignWxValue(STC_CMD_ZOOMOUT);
	Gura_AssignWxValue(STC_CMD_DELWORDLEFT);
	Gura_AssignWxValue(STC_CMD_DELWORDRIGHT);
	Gura_AssignWxValue(STC_CMD_DELWORDRIGHTEND);
	Gura_AssignWxValue(STC_CMD_LINECUT);
	Gura_AssignWxValue(STC_CMD_LINEDELETE);
	Gura_AssignWxValue(STC_CMD_LINETRANSPOSE);
	Gura_AssignWxValue(STC_CMD_LINEDUPLICATE);
	Gura_AssignWxValue(STC_CMD_LOWERCASE);
	Gura_AssignWxValue(STC_CMD_UPPERCASE);
	Gura_AssignWxValue(STC_CMD_LINESCROLLDOWN);
	Gura_AssignWxValue(STC_CMD_LINESCROLLUP);
	Gura_AssignWxValue(STC_CMD_DELETEBACKNOTLINE);
	Gura_AssignWxValue(STC_CMD_HOMEDISPLAY);
	Gura_AssignWxValue(STC_CMD_HOMEDISPLAYEXTEND);
	Gura_AssignWxValue(STC_CMD_LINEENDDISPLAY);
	Gura_AssignWxValue(STC_CMD_LINEENDDISPLAYEXTEND);
	Gura_AssignWxValue(STC_CMD_HOMEWRAP);
	Gura_AssignWxValue(STC_CMD_HOMEWRAPEXTEND);
	Gura_AssignWxValue(STC_CMD_LINEENDWRAP);
	Gura_AssignWxValue(STC_CMD_LINEENDWRAPEXTEND);
	Gura_AssignWxValue(STC_CMD_VCHOMEWRAP);
	Gura_AssignWxValue(STC_CMD_VCHOMEWRAPEXTEND);
	Gura_AssignWxValue(STC_CMD_LINECOPY);
	Gura_AssignWxValue(STC_CMD_WORDPARTLEFT);
	Gura_AssignWxValue(STC_CMD_WORDPARTLEFTEXTEND);
	Gura_AssignWxValue(STC_CMD_WORDPARTRIGHT);
	Gura_AssignWxValue(STC_CMD_WORDPARTRIGHTEXTEND);
	Gura_AssignWxValue(STC_CMD_DELLINELEFT);
	Gura_AssignWxValue(STC_CMD_DELLINERIGHT);
	Gura_AssignWxValue(STC_CMD_PARADOWN);
	Gura_AssignWxValue(STC_CMD_PARADOWNEXTEND);
	Gura_AssignWxValue(STC_CMD_PARAUP);
	Gura_AssignWxValue(STC_CMD_PARAUPEXTEND);
	Gura_AssignWxValue(STC_CMD_LINEDOWNRECTEXTEND);
	Gura_AssignWxValue(STC_CMD_LINEUPRECTEXTEND);
	Gura_AssignWxValue(STC_CMD_CHARLEFTRECTEXTEND);
	Gura_AssignWxValue(STC_CMD_CHARRIGHTRECTEXTEND);
	Gura_AssignWxValue(STC_CMD_HOMERECTEXTEND);
	Gura_AssignWxValue(STC_CMD_VCHOMERECTEXTEND);
	Gura_AssignWxValue(STC_CMD_LINEENDRECTEXTEND);
	Gura_AssignWxValue(STC_CMD_PAGEUPRECTEXTEND);
	Gura_AssignWxValue(STC_CMD_PAGEDOWNRECTEXTEND);
	Gura_AssignWxValue(STC_CMD_STUTTEREDPAGEUP);
	Gura_AssignWxValue(STC_CMD_STUTTEREDPAGEUPEXTEND);
	Gura_AssignWxValue(STC_CMD_STUTTEREDPAGEDOWN);
	Gura_AssignWxValue(STC_CMD_STUTTEREDPAGEDOWNEXTEND);
	Gura_AssignWxValue(STC_CMD_WORDLEFTEND);
	Gura_AssignWxValue(STC_CMD_WORDLEFTENDEXTEND);
	Gura_AssignWxValue(STC_CMD_WORDRIGHTEND);
	Gura_AssignWxValue(STC_CMD_WORDRIGHTENDEXTEND);
	Gura_AssignWxValue(STC_CMD_VERTICALCENTRECARET);
	Gura_AssignWxValue(STC_CMD_MOVESELECTEDLINESUP);
	Gura_AssignWxValue(STC_CMD_MOVESELECTEDLINESDOWN);
	Gura_AssignWxValue(STC_CMD_SCROLLTOSTART);
	Gura_AssignWxValue(STC_CMD_SCROLLTOEND);
	// assignment of functions
	Gura_AssignFunction(StyledTextCtrlEmpty);
	Gura_AssignFunction(StyledTextCtrl);
	// assignment of methods
	
	// assignment of events
	Gura_AssignWxEvent(EVT_STC_CHANGE,					EVT_STC_CHANGE,					StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_STYLENEEDED,				EVT_STC_STYLENEEDED,			StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_CHARADDED,				EVT_STC_CHARADDED,				StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_SAVEPOINTREACHED,		EVT_STC_SAVEPOINTREACHED,		StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_SAVEPOINTLEFT,			EVT_STC_SAVEPOINTLEFT,			StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_ROMODIFYATTEMPT,			EVT_STC_ROMODIFYATTEMPT,		StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_KEY,						EVT_STC_KEY,					StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_DOUBLECLICK,				EVT_STC_DOUBLECLICK,			StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_UPDATEUI,				EVT_STC_UPDATEUI,				StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_MODIFIED,				EVT_STC_MODIFIED,				StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_MACRORECORD,				EVT_STC_MACRORECORD,			StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_MARGINCLICK,				EVT_STC_MARGINCLICK,			StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_NEEDSHOWN,				EVT_STC_NEEDSHOWN,				StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_PAINTED,					EVT_STC_PAINTED,				StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_USERLISTSELECTION,		EVT_STC_USERLISTSELECTION,		StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_URIDROPPED,				EVT_STC_URIDROPPED,				StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_DWELLSTART,				EVT_STC_DWELLSTART,				StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_DWELLEND,				EVT_STC_DWELLEND,				StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_START_DRAG,				EVT_STC_START_DRAG,				StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_DRAG_OVER,				EVT_STC_DRAG_OVER,				StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_DO_DROP,					EVT_STC_DO_DROP,				StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_ZOOM,					EVT_STC_ZOOM,					StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_HOTSPOT_CLICK,			EVT_STC_HOTSPOT_CLICK,			StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_HOTSPOT_DCLICK,			EVT_STC_HOTSPOT_DCLICK,			StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_CALLTIP_CLICK,			EVT_STC_CALLTIP_CLICK,			StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_AUTOCOMP_SELECTION,		EVT_STC_AUTOCOMP_SELECTION,		StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_INDICATOR_CLICK,			EVT_STC_INDICATOR_CLICK,		StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_INDICATOR_RELEASE,		EVT_STC_INDICATOR_RELEASE,		StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_AUTOCOMP_CANCELLED,		EVT_STC_AUTOCOMP_CANCELLED,		StyledTextEvent);
	Gura_AssignWxEvent(EVT_STC_AUTOCOMP_CHAR_DELETED,	EVT_STC_AUTOCOMP_CHAR_DELETED,	StyledTextEvent);
}

Gura_ImplementDescendantCreator(wx_StyledTextCtrl)
{
	return new Object_wx_StyledTextCtrl((pClass == NULL)? this : pClass, NULL, NULL, OwnerFalse);
}

Gura_EndModuleScope(wx)
